first commit for messages CRUD
Borodutch/backend-starter pull request #102
Opened 2022-03-20 21:53 UTC by i1d

+model for storing messages
+controller for handling CRUD

2022-03-20 21:59 UTC, backmeupplz requested changes

2022-03-20 21:59 UTC, backmeupplz commented on src/models/message.ts
> +  strippedAndFilled({
Эта функция тебе не нужна

2022-03-20 21:59 UTC, backmeupplz commented on src/models/message.ts
> +  messageText!: string
Назови это просто `text`

2022-03-20 21:59 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ index: true, lowercase: false, unique: false }) //does it need index?
`index` тут точно не нужен, почитай, почему. Почитай, что такое `unique: false`, это не то, что тебе нужно.

2022-03-20 21:59 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ index: true, lowercase: false, unique: false }) //does it need index?
Почитай, что такое `lowercase: false` тоже.

2022-03-20 21:59 UTC, backmeupplz commented on src/models/message.ts
> +  token?: string
Сообщению токен не нужен

2022-03-20 21:59 UTC, backmeupplz commented on src/models/message.ts
> +  author!: string
Сделай автора через `ref` в `typegoose`

2022-03-20 21:59 UTC, backmeupplz commented on src/models/message.ts
> +export async function findOrCreateMessage(messageOptions: {
Эта функция тебе не нужна

2022-03-20 21:59 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +@Controller('/')
Это не базовый контроллер, тут нужен буть `/messages`

2022-03-20 21:59 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +  @Get('/read')
Сделай просто `GET /messages`, который возвращает все сообщения пользователя

2022-03-20 21:59 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +    console.log('inside GET READ')
Не пушь лишние `console.log` в PR

2022-03-20 21:59 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +      console.log('No messages found')
Если хочешь кинуть ошибку, используй `ctx.throw` и `@hapi/boom`

2022-03-20 21:59 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +    // @Query('email') email?: string // @Query('author') author: string
Не пушь закомментированный код в PR

2022-03-20 22:03 UTC, i1d commented on src/models/message.ts
> +  strippedAndFilled({
Убрал

2022-03-21 07:06 UTC, i1d commented on src/models/message.ts
> +  @prop({ index: true, lowercase: false, unique: false }) //does it need index?
> `index` тут точно не нужен, почитай, почему. Почитай, что такое `unique: false`, это не то, что тебе нужно.

Не нужен, потому что будет занимать большой объем? https://docs.mongodb.com/manual/core/index-text/#storage-requirements-and-performance-costs 

На сколько я понял, "unique: false" не имеет смысла. Если мне нужен индекс по полю, в котором должны быть уникальные значения - я пишу "unique: true", в противном случае - не пишу ничего. https://docs.mongodb.com/manual/core/index-unique/#unique-indexes

2022-03-21 07:11 UTC, i1d commented on src/models/message.ts
> +  @prop({ index: true, lowercase: false, unique: false }) //does it need index?
> Почитай, что такое `lowercase: false` тоже.

Писать "lowercase: false" тоже не имеет смысла, т.к. "lowercase: true" будет вызывать ".toLowerCase()", а если ничего не написать - то ничего и не будет вызываться:

https://mongoosejs.com/docs/schematypes.html
String
lowercase: boolean, whether to always call .toLowerCase() on the value

2022-03-21 10:59 UTC, i1d reviewed
отработал комментарии

2022-03-21 17:32 UTC, backmeupplz requested changes

2022-03-21 17:32 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ index: true, required: true })
Без `ref:` не будет работать, почитай документацию о `ref` в typegoose

2022-03-21 17:32 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +import * as boom from '@hapi/boom'
Не используй unnamed imports

2022-03-21 17:32 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +      ctx.throw(boom.notFound('No messages found'))
Не забывай делать return

2022-03-21 17:32 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +      ctx.throw(boom.notFound('No messages found'))
Давай не будем пока что добавлять строки в ошибки

2022-03-21 17:32 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +    console.log(`Messages: ${messages}`)
Не пушь лишние комментарии в PR

2022-03-21 17:32 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +    if (!newMessage) {
Почти никогда этого не будет

2022-03-21 17:32 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +import * as boom from '@hapi/boom'
Создай новый метод в login контроллере, который принимает `email` и `name`, без пароля, для тестов. Создай middleware, который будет проверять token пользователя, который добавляется во все реквесты в `headers.token`. Пользователя можешь закинуть в `ctx.state.user` — и использовать в методах контроллера

2022-03-22 13:11 UTC, i1d commented on src/controllers/crud_messages.ts
> +      ctx.throw(boom.notFound('No messages found'))
> Не забывай делать return

Но ведь return внутри if не будет выполняться после ctx.throw()... Или я не так понял?

2022-03-22 13:39 UTC, i1d commented on src/controllers/crud_messages.ts
> +      ctx.throw(boom.notFound('No messages found'))
> > Не забывай делать return
> 
> Но ведь return внутри if не будет выполняться после ctx.throw()... Или я не так понял?

А, можно же сделать return ctx.throw(...)...

2022-03-23 21:03 UTC, i1d commented on src/controllers/crud_messages.ts
> +import * as boom from '@hapi/boom'
Пока добавил middleware перед POST...

2022-03-23 21:51 UTC, backmeupplz requested changes

2022-03-23 21:51 UTC, backmeupplz commented on src/validators/emailLogin.ts
> +export default class {
Либо добавляй пустые строки между импортом и кодом, либо нет :) но нужно быть последовательными

2022-03-23 21:51 UTC, backmeupplz commented on src/validators/emailLogin.ts
> +export default class {
Если это класс, но название файла должно быть с большой буквы

2022-03-23 21:51 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ index: true, required: true, ref: () => User, type: () => String })
`type` тут не нужен, это `ref`

2022-03-23 21:51 UTC, backmeupplz commented on src/models/message.ts
> +  author!: Ref<User, string>
второй аргумент в дженерике не нужен, это просто `Ref<User>`

2022-03-23 21:51 UTC, backmeupplz commented on src/middlewares/email.ts
> +export default async function emailMiddleware(ctx: Context, next: () => void) {
Выглядит, как `authMiddleware`

2022-03-23 21:51 UTC, backmeupplz commented on src/middlewares/email.ts
> +export default async function emailMiddleware(ctx: Context, next: () => void) {
Найти правильный тип функции `next`

2022-03-23 21:51 UTC, backmeupplz commented on src/middlewares/email.ts
> +  const user = await UserModel.findOne({ token })
Давай еще проверим сам jwt токен через один из модулей в `helpers`

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +  async findAllMessages(@Ctx() ctx: Context) {
Нужно находить только сообщения этого пользователя

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +  @Get('/users')
Это пошло бы в контроллер `users`, а не `messages` :)

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +import { Context } from 'koa'
назови файл коротко

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +  @Get('/user/:token')
Это явно не метод контроллера messages

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +  async findMessageById(@Params('id') id: ObjectId, @Ctx() ctx: Context) {
Валидируй Params

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +      //if ctx.state.user !== @Query('author') => throw an error
Не пушь в гит закомментированный код

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +    @Query('author') author: string,
У тебя тут не должно быть `Query`, должен быть `Body`

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +  @Post('/create')
Можно просто написать `'/'`

2022-03-23 21:51 UTC, backmeupplz commented on src/controllers/crud_messages.ts
> +  @Delete('/delete/:id')
У тебя в названии метода `Delete`, тебе не нужно добавлять еще `/delete`

2022-03-25 08:52 UTC, i1d commented on src/models/message.ts
> +  @prop({ index: true, required: true, ref: () => User, type: () => String })
Почему-то все ломается, если убрать type: () => String...
Разбираюсь...

2022-03-25 08:59 UTC, i1d commented on src/middlewares/email.ts
> +export default async function emailMiddleware(ctx: Context, next: () => void) {
> Найти правильный тип функции `next`

Если указать next: Function - то eslint начинает ругаться.. это можно игнорировать?

2022-03-25 09:02 UTC, i1d commented on src/controllers/crud_messages.ts
> +      //if ctx.state.user !== @Query('author') => throw an error
Тут это был комментарий к коду... поправил

2022-03-25 09:21 UTC, i1d commented on src/controllers/crud_messages.ts
> +  @Get('/users')
Переместил)

2022-03-25 09:22 UTC, i1d commented on src/controllers/crud_messages.ts
> +  @Get('/user/:token')
Переместил)

2022-03-25 23:38 UTC, i1d reviewed
+fixes

2022-03-25 23:48 UTC, backmeupplz requested changes

2022-03-25 23:48 UTC, backmeupplz commented on src/validators/emailLogin.ts
> +import { IsEmail, IsString } from 'amala'
Если у класса название с большой буквы и это единственный экспорт, то и у файла должно быть название с большой буквы

2022-03-25 23:48 UTC, backmeupplz commented on src/validators/emailLogin.ts
> +import { IsEmail, IsString } from 'amala'
Разберись, как в гите менять регистр букв в файлах

2022-03-25 23:48 UTC, backmeupplz commented on src/middlewares/email.ts
> +  const _token = verify(token)
Никогда не начинай в TS переменные с `_` — это плохой тон

2022-03-25 23:48 UTC, backmeupplz commented on src/middlewares/email.ts
> +  const _token = verify(token)
Результат `verify` будет не строкой

2022-03-25 23:48 UTC, backmeupplz commented on src/middlewares/email.ts
> +  if (!_token) {
`verify` либо кинет ошибку, либо вернет payload, но никогда не вернет falsy value

2022-03-25 23:48 UTC, backmeupplz commented on src/controllers/users.ts
> +@Controller('/users')
Тебе не нужен контроллер `users`

2022-03-25 23:48 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const message = await MessageModel.findById(id)
Постоянно ищешь `message`, из-за этого повторяешь один и тот же код. Может, выведем в middleware? И там же сразу проверим, принадлежит ли message пользователю, который его запросил?

2022-03-25 23:48 UTC, backmeupplz commented on src/controllers/messages.ts
> +    if (!messages) {
`find` никогда не возвращает falsy value. Если не найдет сообщения, вернет `[]`. Вряд ли нужно возвращать ошибку, вернуть `[]`, если нет сообщений, вполне нормально

2022-03-25 23:48 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.create({ author: currentUser, text })
Тебе не нужен `return await`. Почитай, что такое `return await` и как связаны `promises` и `async/await`.

2022-03-27 00:04 UTC, i1d reviewed
+ message middleware
+ patch validation
+ delete validation
+ minor fixes
+ removed users controller

2022-03-27 00:25 UTC, backmeupplz requested changes

2022-03-27 00:25 UTC, backmeupplz commented on src/middlewares/emailMiddleware.ts
> +export default async function emailMiddleware(ctx: Context, next: Function) {
Это, скорре, `authMiddleware`, про `email` тут ничего нет

2022-03-27 00:25 UTC, backmeupplz commented on src/middlewares/emailMiddleware.ts
> +  if (token === undefined) {
Это проверяется просто `if (!token)`

2022-03-27 00:25 UTC, backmeupplz commented on src/middlewares/emailMiddleware.ts
> +    return ctx.throw(badRequest())
Нет смысла делать `return/else`, погугли, почему

2022-03-27 00:25 UTC, backmeupplz commented on src/middlewares/emailMiddleware.ts
> +      const verifiedToken = verify(token)
Если ты дальше не используешь `verifiedToken`, то нет смысла создавать эту переменную

2022-03-27 00:25 UTC, backmeupplz commented on src/middlewares/messageMiddleware.ts
> +  const user = ctx.state.user._id
Это же `userId`, а не `user`

2022-03-27 00:25 UTC, backmeupplz commented on src/middlewares/messageMiddleware.ts
> +    return ctx.throw(notAcceptable())
утекает информация о существовании сообщения, нужно возвращать `notFound` :) тогда злоумышленник не узнает даже о существовании чужого сообщения

2022-03-27 00:25 UTC, backmeupplz commented on src/controllers/messages.ts
> +  @Flow(emailMiddleware)
Если ты везде используешь `emailMiddleware`, то просто повесь ее прямо на контроллер

2022-03-27 00:25 UTC, backmeupplz commented on src/controllers/messages.ts
> +  findMessageById(@State('message') message: MessageValidator) {
Тебе не нужно валидировать `message`. Просто укажи, что тип тут — `Message`

2022-03-27 00:25 UTC, backmeupplz commented on src/controllers/messages.ts
> +  @Patch('/update/:id')
Тебе не нужно писать `/update/:id`, можешь просто `/:id`

2022-03-27 00:25 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const updMessage = await MessageModel.findByIdAndUpdate(
Не скоращай названия переменных без надобности

2022-03-27 10:24 UTC, i1d reviewed
minor fixes

2022-03-27 14:13 UTC, backmeupplz requested changes

2022-03-27 14:13 UTC, backmeupplz commented on src/middlewares/messageMiddleware.ts
> +  const message = await MessageModel.findById({ _id: id })
Можно просто передать `.findById(id)`

2022-03-27 14:13 UTC, backmeupplz commented on src/middlewares/authMiddleware.ts
> +  if (!token) {
Стоит эту проверку перенести над проверкой выше

2022-03-27 14:13 UTC, backmeupplz commented on src/controllers/messages.ts
> +  findAllMessages(@CurrentUser() currentUser: User) {
А если назовешь перменную `author`, то сможешь сделать `{ author }`

2022-03-27 14:13 UTC, backmeupplz commented on src/controllers/messages.ts
> +    @CurrentUser() currentUser: User
Тут тоже можно назвать `author`

2022-03-27 14:13 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const updatedMessage = await MessageModel.findByIdAndUpdate(
Можешь просто сделать тут `return MessageModel.findByIdAndUpdate(...)`

2022-03-27 14:13 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const delMessage = await MessageModel.findByIdAndDelete(message)
Можешь тут просто сделать `return MessageModel.findByIdAndDelete(...)`

2022-03-27 19:24 UTC, i1d reviewed
minor fixes

2022-03-27 21:19 UTC, backmeupplz requested changes

2022-03-27 21:19 UTC, backmeupplz commented on src/middlewares/authMiddleware.ts
> +export default async function emailMiddleware(ctx: Context, next: Function) {
Это же `authMiddleware`

2022-03-27 21:19 UTC, backmeupplz commented on src/middlewares/authMiddleware.ts
> +export default async function emailMiddleware(ctx: Context, next: Function) {
`next` дай нормальный тип

2022-03-27 21:19 UTC, backmeupplz commented on src/middlewares/messageMiddleware.ts
> +export default async function messageMiddleware(ctx: Context, next: Function) {
У `next` должен быть нормальный тип

2022-03-27 22:50 UTC, i1d reviewed
next type fix; linter fix

2022-03-29 18:57 UTC, backmeupplz requested changes

2022-03-29 18:57 UTC, backmeupplz commented on src/models/message.ts
> +export class Message {
Названия файлов классов, как и названия классов, должны писаться с большой буквы

2022-07-01 22:59 UTC, closed without merging