added CRUD messages
Borodutch/backend-starter pull request #104
Opened 2022-04-02 17:26 UTC by JKurero

- added CRUD messages

2022-04-02 22:51 UTC, backmeupplz requested changes

2022-04-02 22:51 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +// import { msgNeedId, msgNoId } from '@/validators/Messages'
Не пушь закомментированный код в git

2022-04-02 22:51 UTC, backmeupplz commented on src/models/Message.ts
> +const msgModel = getModelForClass(Message)
Не сокращай зазря названия переменных

2022-04-02 22:51 UTC, backmeupplz commented on src/models/Message.ts
> +  id?: string
`id` уже есть в `Message`, не нужно лишний раз его объявлять

2022-04-02 22:51 UTC, backmeupplz commented on src/models/Message.ts
> +  title?: string
Достаточно будет `text!: string`, подсказка: required

2022-04-02 22:51 UTC, backmeupplz commented on src/models/Message.ts
> +  description?: string
`description` не нужен, зато нужен `author`

2022-04-02 22:51 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +      .then(async function () {
Почитай про `async/await` и `promises` — и как они связаны. Не мешай `async/await` и `then/catch`

2022-04-02 22:51 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +interface msgObj {
Тебе не нужен этот интерфейс

2022-04-03 14:21 UTC, backmeupplz requested changes

2022-04-03 14:21 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +  @Post('')
Лучше делать `@Post('/')`

2022-04-03 14:21 UTC, backmeupplz commented on src/validators/message.ts
> +export default class MessageObject {
Если эскпортишь только один класс — и он написан с большой буквы, то и файл должен быть назван так же и с большой буквы

2022-04-03 14:21 UTC, backmeupplz commented on src/models/Message.ts
> +  author!: string
Это должен быть `ref`, почитай, что это такое в документации typegoose

2022-04-03 14:21 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +  const message = await MessageModel.findOne({ _id: id }).catch((error) => {
Используй `async/await`, а не `then/catch`

2022-04-03 14:21 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +    return { error }
Разберись с тем, как работают Promises, эта ошибка вернется вникуда

2022-04-03 14:21 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +async function getMessageById(id: string) {
Этой функции не должно быть в этом файле

2022-04-03 14:21 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +    return {
А можно сделать просто `return MessageModel.create(message)`

2022-04-03 14:21 UTC, backmeupplz commented on src/models/Message.ts
> +const messageModel = getModelForClass(Message)
Здесь с маленькой буквы названа модель, а там, где используешь — с большой. Будь последовательным

2022-04-03 14:21 UTC, backmeupplz commented on src/controllers/messagesController.ts
> +      return {
Если появляются ошибки, тебе нужно их кидать, как `@hapi/boom` ошибки, а не возвращать из метода. Почитай про `try/catch`

2022-04-03 15:40 UTC, JKurero commented on src/controllers/messagesController.ts
> +  const message = await MessageModel.findOne({ _id: id }).catch((error) => {
Блин, точно, пропустил :(.

2022-04-03 15:45 UTC, JKurero commented on src/controllers/messagesController.ts
> +async function getMessageById(id: string) {
Я вообще создавал эту функцию, как вспомогательную для PUT, а потом узнал, что есть опция `{ new : true }`. Думаю, её вообще стоит убрать. Нет возражений?

2022-04-05 14:58 UTC, backmeupplz requested changes

2022-04-05 14:58 UTC, backmeupplz commented on package.json
>    "dependencies": {
В этом файле не должно быть изменений

2022-04-05 14:58 UTC, backmeupplz commented on yarn.lock
>    languageName: node
В этом файле не должно быть изменений

2022-04-05 14:58 UTC, backmeupplz commented on src/validators/MessageValidator.ts
> +  @IsString()
Есть `IsMongoId` декоратор

2022-04-05 14:58 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +
Создай новый метод в login контроллере, например, `/email`, который будет принимать имя и имейл (без пароля для этой задачи) — и возвращать пользователя.

Токен этого пользователя надо добавлять в headers реквестов, например, в хедер `token`. Создай middleware, которая будет использовать `helpers/jwt` для верификации валидности токена, находить пользователя по этому токену и добавлять его в `ctx.state.user`. А потом почитай про доступные декораторы в `amala` и подумай, какие нужно использовать :)

2022-04-07 22:51 UTC, backmeupplz requested changes

2022-04-07 22:51 UTC, backmeupplz commented on src/helpers/userVerificator.ts
> +  if (token) {
Fail first. Сначала проверь, вдруг нет `token` и кинь `@hapi/boom` ошибку, а потом продолжай, как обычно

2022-04-07 22:51 UTC, backmeupplz commented on src/helpers/userVerificator.ts
> +    const result = verify(token.toString())
`verify` кинет ошибку, если результата нет, можно не проверять на `if (result)`

2022-04-07 22:51 UTC, backmeupplz commented on src/helpers/userVerificator.ts
> +      const user = await UserModel.findOne({ _id: result.id })
Ищи прямо по `token`

2022-04-07 22:51 UTC, backmeupplz commented on src/helpers/runApp.ts
> +  app.use(errorHandler)
В этом файле не должно быть изменений

2022-04-07 22:51 UTC, backmeupplz commented on src/helpers/errorHandler.ts
> +import { Context, Next } from 'koa'
Этот файл не нужен

2022-04-07 22:51 UTC, backmeupplz commented on src/controllers/login.ts
> +  @Post('/email')
Либо добавляй пустые строки между функциями, либо нет — но будь последовательным

2022-04-07 22:51 UTC, backmeupplz commented on src/controllers/login.ts
> +    return UserModel.findOne(body)
Посмотри на то, что делают другие методы в этом контроллере. Как ты найдешь пользователя, если у тебя нет возможности его создать?

2022-04-07 22:51 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +    @Body({ required: true }) body: { text: string; author: string }
`body` нужно валидировать

2022-04-07 22:51 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +    return MessageModel.create(body)
Нельзя пускать в `create` непроверенный ввод от пользователя, тебе нужно сделать `destruct` аргумента body и использовать тут внутренности

2022-04-07 22:51 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +    @Body({ required: true }) body: { text: string; author: string }
У тебя `author` стоит как `required` и с типом `Ref<User>`, а не `string`. Это работать не будет, почини.

2022-04-08 14:49 UTC, backmeupplz requested changes

2022-04-08 14:49 UTC, backmeupplz commented on src/validators/MessageValidator.ts
> +import { IsString } from 'amala'
Давай уберем `Validator` из названия класса и файла

2022-04-08 14:49 UTC, backmeupplz commented on src/validators/UserValidator.ts
> +import { IsEmail, IsMongoId, IsString } from 'amala'
Тебе этот валидатор не нужен

2022-04-08 14:49 UTC, backmeupplz commented on src/controllers/login.ts
> +    return findOrCreateUser({ email, name })
Не забывай сделать `strippedAndFilled`, иначе утекут ненужные поля тому, кто этого пользователя создает

2022-04-08 14:49 UTC, backmeupplz commented on src/helpers/userVerificator.ts
> +export default async function userVerificator(ctx: Context, next: Next) {
Давай назовем этот миддлварь `authenticate`

2022-04-08 14:49 UTC, backmeupplz commented on src/helpers/userVerificator.ts
> +    throw notFound()
Тут скорее надо кидать `403` или `401`

2022-04-08 14:49 UTC, backmeupplz commented on src/helpers/userVerificator.ts
> +  verify(token.toString())
Сделай `try/catch` и кинь `403` в `catch` — иначе будет падать 500 с сервера

2022-04-08 14:49 UTC, backmeupplz commented on src/helpers/userVerificator.ts
> +  await next()
Нет смысла делать `await`, когда можно сделать `return`. Почитай, как работают `promises`

2022-04-08 14:49 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +    @CurrentUser() author: UserValidator
Это же `DocumentType<User>` :) Почитай про то, что это

2022-04-08 14:49 UTC, backmeupplz commented on src/validators/MessageValidator.ts
> +import { IsString } from 'amala'
Можно назвать, например, `MessageBody`

2022-04-08 14:49 UTC, backmeupplz commented on src/helpers/findMessage.ts
> +export default async function (messageId: string, currentUserId: string) {
Выглядит, как будто это должна была быть `middleware`, которая найденное сообщение еще и добавляет в `ctx.state` для использования позже :)

2022-04-08 14:49 UTC, backmeupplz commented on src/helpers/findMessage.ts
> +  if (currentUserId.toString() !== message?.author?.toString()) {
Подскажу, что `user.id` — это `user._id.toString()`

2022-04-10 14:25 UTC, backmeupplz requested changes

2022-04-10 14:25 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +    return ctx.state.message.delete()
Есть декоратор `@State`

2022-04-10 20:52 UTC, backmeupplz requested changes

2022-04-10 20:52 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +  deleteMessage(@State('message') message: DocumentType<MessageBody>) {
Это `DocumentType<Message>`

2022-04-10 20:52 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +  deleteMessage(@State('message') message: DocumentType<MessageBody>) {
Валидировать `@State` не нужно

2022-04-10 20:52 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +    const author = user.strippedAndFilled()
Тебе не нужно делать `strippedAndFilled` здесь, а `user` ты сразу можешь назвать `author`

2022-04-11 14:25 UTC, backmeupplz requested changes

2022-04-11 14:25 UTC, backmeupplz commented on src/models/MessageModel.ts
> +import { Ref, getModelForClass, modelOptions, prop } from '@typegoose/typegoose'
Назови этот файл просто `Message`

2022-04-11 14:25 UTC, backmeupplz commented on src/helpers/confirmAuthorship.ts
> +    return next()
Тут должна кидаться ошибка. Нельзя проверить авторство сообщения без сообщения.

2022-04-11 14:25 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +  getMessages(@CurrentUser() { _id }: DocumentType<User>) {
А можешь не дестрактить тут, а просто взять `author` и кинуть внизу в query :)

2022-04-11 16:05 UTC, backmeupplz requested changes

2022-04-11 16:05 UTC, backmeupplz commented on src/controllers/MessageController.ts
> +    return MessageModel.create({ author: author._id, text })
Можно просто `return MessageModel.create({ author, text })` :)

2022-04-13 13:46 UTC, closed without merging