CRUD messages
Borodutch/backend-starter pull request #106
Opened 2022-04-21 11:29 UTC by ivan-41

Add message model and koa router for get, post, put and delete requests.

2022-04-21 14:15 UTC, backmeupplz requested changes

2022-04-22 19:22 UTC, backmeupplz requested changes

2022-04-22 19:22 UTC, backmeupplz commented on src/controllers/message.ts
> +    @Get('/') // +
Не пушь лишние комментарии

2022-04-22 19:22 UTC, backmeupplz commented on src/controllers/message.ts
> +        return await Message.find({})
Почитай, как `promises` связаны с `async/await`, а потом про `return await`

2022-04-22 19:22 UTC, backmeupplz commented on src/controllers/message.ts
> +
Лучше использовать одну пустую строку

2022-04-22 19:22 UTC, backmeupplz commented on src/controllers/message.ts
> +        return await Message.create(ctx.request.body)
Используй `@Body` и валидируй его, как в другом контроллере

2022-04-22 19:22 UTC, backmeupplz commented on src/controllers/message.ts
> +    async editMessage (@Ctx() ctx: Context) {
Используй `@Params` и влаидируй его

2022-04-22 19:22 UTC, backmeupplz commented on src/models/messagemodel.ts
> +    public posting_date?: string
Не используй snake case, используй camel case

2022-04-22 19:22 UTC, backmeupplz commented on src/models/messagemodel.ts
> +    @prop()
Не оставляй `@prop` пустыми

2022-04-22 19:22 UTC, backmeupplz commented on src/models/messagemodel.ts
> +class messages {
Это класс, классы пишутся с большой буквы

2022-04-22 19:22 UTC, backmeupplz commented on src/models/messagemodel.ts
> +//const mongoose = require('mongoose')
Не пушь закомментированный код

2022-04-22 19:22 UTC, backmeupplz commented on src/models/messagemodel.ts
> +//const mongoose = require('mongoose')
Называй файлы по названиям классов, которые экспортишь :)

2022-04-22 19:22 UTC, backmeupplz commented on src/models/messagemodel.ts
> +/*const Schema = mongoose.Schema
Не пушь закомментированный код

2022-04-22 19:32 UTC, ivan-41 commented on src/models/messagemodel.ts
> +class messages {
Сделал с большой

2022-04-22 19:34 UTC, ivan-41 commented on src/models/messagemodel.ts
> +/*const Schema = mongoose.Schema
Убрал код из комментариев

2022-04-22 19:47 UTC, ivan-41 commented on src/helpers/runApp.ts
Убрал изменения, сделал в папке controllers контроллер на amala

2022-04-22 19:48 UTC, ivan-41 commented on src/controllers/message.ts
> +
Ок, не буду оставлять 2 строки

2022-04-22 19:50 UTC, ivan-41 commented on src/controllers/message.ts
> +    @Get('/') // +
Да, это я отмечал работоспособность кода, смысла они не несут. Убираю

2022-04-23 20:36 UTC, ivan-41 commented on src/models/messagemodel.ts
> +    public posting_date?: string
Переделал

2022-04-23 20:57 UTC, ivan-41 commented on src/models/messagemodel.ts
> +    @prop()
Заполнил

2022-04-23 21:10 UTC, ivan-41 commented on src/controllers/message.ts
> +        return await Message.find({})
А, то есть я увеличил время выполнения просто так, использовав return await

2022-04-24 14:21 UTC, ivan-41 commented on src/controllers/message.ts
> +        return await Message.create(ctx.request.body)
Сделал валидатор для Body

2022-04-24 14:24 UTC, ivan-41 commented on src/controllers/message.ts
> +    async editMessage (@Ctx() ctx: Context) {
Добавил @Params

2022-04-24 14:40 UTC, backmeupplz requested changes

2022-04-24 14:40 UTC, backmeupplz commented on src/helpers/runApp.ts
> -
В этом файле не должно быть изменений

2022-04-24 14:40 UTC, backmeupplz commented on src/models/messagemodel.ts
> +class Messages {
Это `Message`

2022-04-24 14:40 UTC, backmeupplz commented on src/models/messagemodel.ts
> +import { getModelForClass, prop } from '@typegoose/typegoose'
Называй файл так, как называешь экспортируемый класс

2022-04-24 14:40 UTC, backmeupplz commented on src/models/messagemodel.ts
> +    public postingDate?: string
Тебе нужен `timestamps`, посмотри в файл, который рядом. Тебе не нужно указывать эту опцию

2022-04-24 14:40 UTC, backmeupplz commented on src/models/messagemodel.ts
> +    public postingDate?: string
`public` можно не писать, это дефолтное значение

2022-04-24 14:40 UTC, backmeupplz commented on src/models/messagemodel.ts
> +    public postingDate?: string
Написано `required: true`, то тип опциональный: `?: string`. Так опционально или нет?

2022-04-24 14:40 UTC, backmeupplz commented on src/models/messagemodel.ts
> +    public authorName?: string
Это должен быть `ref` из `typegoose`

2022-04-24 14:40 UTC, backmeupplz commented on src/models/messagemodel.ts
> +    public messageBody?: string
Достаточно просто назвать это `text`

2022-04-24 14:40 UTC, backmeupplz commented on src/controllers/message.ts
> +        @Body({ required: true }) body: CorrectMessage
Сделай `deconstruct`, не передавай все, что посылает кто угодно в этот метод, напрямую в `Message.create`

2022-04-24 14:40 UTC, backmeupplz commented on src/controllers/message.ts
> +        return Message.create(ctx.request.body)
Зачем тебе переменная `body`, если ты ее не используешь?

2022-04-24 14:40 UTC, backmeupplz commented on src/controllers/message.ts
> +        @Body({ required: true }) body: CorrectMessage,
Ты не `body`, не `id` не использовал в этом методе

2022-04-24 14:40 UTC, backmeupplz commented on src/controllers/message.ts
> +        @Params('id') id: number
Валидируй `@Params() { id }`

2022-09-19 21:39 UTC, closed without merging