sovetovm created CRUD
Borodutch/backend-starter pull request #108
Opened 2022-04-27 21:34 UTC by sovetovm

- Добавил crud.ts -> controllers
- Добавил msg.ts -> models

2022-04-27 21:38 UTC, backmeupplz requested changes

2022-04-27 21:38 UTC, backmeupplz commented on src/controllers/crud.ts
> +import { Controller, Ctx, Get, Post, Put, Delete } from 'amala'
Давай назовем этот файл `Messages.ts`

2022-04-27 21:38 UTC, backmeupplz commented on src/controllers/crud.ts
> +@Controller('/crud')
Тут лучше сделать `/messages`

2022-04-27 21:38 UTC, backmeupplz commented on src/models/msg.ts
> +import { Schema } from "mongoose"
Давай назовем этот файл `Message.ts`

2022-04-27 21:38 UTC, backmeupplz commented on src/models/msg.ts
> +export const MsgSchema = new Schema ({
Не сокращай зазря названия переменных

2022-04-27 21:38 UTC, backmeupplz commented on src/models/msg.ts
> +export const MsgSchema = new Schema ({
Используй typegoose

2022-04-28 15:30 UTC, sovetovm commented on src/controllers/crud.ts
> +import { Controller, Ctx, Get, Post, Put, Delete } from 'amala'
сделал ✅

2022-04-28 15:30 UTC, sovetovm commented on src/controllers/crud.ts
> +@Controller('/crud')
сделал ✅

2022-04-28 15:30 UTC, sovetovm commented on src/models/msg.ts
> +import { Schema } from "mongoose"
сделал ✅

2022-04-28 15:37 UTC, backmeupplz requested changes

2022-04-28 16:49 UTC, sovetovm commented on src/models/msg.ts
> +export const MsgSchema = new Schema ({
✅

2022-04-28 16:49 UTC, sovetovm commented on src/models/Message.ts
> +export const Msg = getModelForClass(Messages)
✅

2022-04-28 16:49 UTC, sovetovm commented on src/controllers/Messages.ts
> +    await Msg.findByIdAndUpdate({ _id: ctx.params.id }, ctx.request.body)
✅

2022-04-28 17:11 UTC, backmeupplz requested changes

2022-04-28 17:11 UTC, backmeupplz commented on src/models/Message.ts
> +  text!: string
Это `optional` или `required`? В `@prop` ничего нет

2022-04-28 17:11 UTC, backmeupplz commented on src/models/Message.ts
> +export const Message = getModelForClass(Messages)
Это скорее `MessageModel`

2022-04-28 17:11 UTC, backmeupplz commented on src/controllers/Messages.ts
> +export default class CrudController {
Это же `MessagesController`

2022-04-28 17:11 UTC, backmeupplz commented on src/controllers/Messages.ts
> +    return Message.create(ctx.request.body)
Зачем ты добавляешь `@Body`, если не используешь его?

2022-04-28 18:08 UTC, sovetovm commented on src/models/Message.ts
> +  text!: string
✅

2022-04-28 18:08 UTC, sovetovm commented on src/models/Message.ts
> +export const Message = getModelForClass(Messages)
✅

2022-04-28 18:09 UTC, sovetovm commented on src/controllers/Messages.ts
> +export default class CrudController {
✅

2022-04-28 18:09 UTC, sovetovm commented on src/controllers/Messages.ts
> +    return Message.create(ctx.request.body)
Думал это такая валидация :)
поправил ✅

2022-04-28 18:10 UTC, sovetovm commented on src/models/Message.ts
> +export class Messages {
✅

2022-04-28 18:11 UTC, sovetovm commented on src/controllers/Messages.ts
> +  createMessage(@Ctx() ctx: Context, @Body() text: Messages) {
Сделал валидатор ✅

2022-04-28 18:17 UTC, backmeupplz commented on src/controllers/Messages.ts
> +    @Params() _id: string
И у тебя в параметрах не `_id`

2022-04-28 18:18 UTC, backmeupplz commented on src/controllers/Messages.ts
> +        { _id: ctx.params.id },
Зачем писать `@Params`, если не используешь его?

2022-05-18 14:46 UTC, backmeupplz commented on src/validators/ValidMessage.ts
> +export default class MessageText {
Файл называется иначе

2022-05-18 14:47 UTC, backmeupplz commented on src/validators/ValidId.ts
> +export default class IdIsAString {
Файл называется иначе

2022-05-18 14:47 UTC, backmeupplz commented on src/controllers/Messages.ts
> +  deleteMessage(@Params('id') id: IdIsAString) {
Посмотри, в чем разница между `@Params('id')`и `@Params()`

2022-05-18 14:47 UTC, backmeupplz commented on src/controllers/Messages.ts
> +    await MessageModel.findByIdAndUpdate({ _id: id }, { text })
Почему бы просто не вернуть результат отсюда?

2022-05-18 14:48 UTC, backmeupplz commented on src/models/Message.ts
> +export class Message {
Автора можно получить, добавив новый метод в контроллер логина. Назови его `email`, чтобы он принимал `email` и `name`, без пароля для нашего теста.

2022-05-18 14:48 UTC, backmeupplz commented on src/models/Message.ts
> +export class Message {
Используй `ref` в `typegoose`

2022-05-18 14:49 UTC, backmeupplz commented on src/models/Message.ts
> +export class Message {
Юзер должен иметь доступ только к своим сообщениям

2022-07-18 19:52 UTC, backmeupplz requested changes

2022-07-18 19:52 UTC, backmeupplz commented on src/models/Message.ts
> +  creator!: Ref<User>
Давай назовем его `author`

2022-07-18 19:52 UTC, backmeupplz commented on src/helpers/creatorAccess.ts
> +import { Context, Next } from 'koa'
У тебя миддлвари как-то сильно по-разному названы. Не режет глаз?

2022-07-18 19:52 UTC, backmeupplz commented on src/helpers/creatorAccess.ts
> +import { Context, Next } from 'koa'
Ну и закинь их не в `helpers`, а в папку `middlewares` :)

2022-07-18 19:52 UTC, backmeupplz commented on src/helpers/authMiddleware.ts
> +    throw new Error('You are not authorized')
А давай везде использовать `@hapi/boom`, чтобы нормальные ошибки возвращал API

2022-07-18 19:52 UTC, backmeupplz commented on src/helpers/creatorAccess.ts
> +  if (!message.creator) {
А такое бывает? Вроде как, поле `required`

2022-07-18 19:52 UTC, backmeupplz commented on src/helpers/creatorAccess.ts
> +  console.log(userId, messageCreator)
Не пушь лишние `console.log` в PR

2022-07-18 19:52 UTC, backmeupplz commented on src/helpers/creatorAccess.ts
> +    throw new Error('Something went terribly wrong...')
Может, ошибка иная?

2022-07-18 19:52 UTC, backmeupplz commented on src/controllers/Messages.ts
> +  showPrivateMessage(@State('message') message: DocumentType<Message>) {
`showPrivateMessage` долго и непонятно. Может, `getMessage`?

2022-07-19 13:18 UTC, backmeupplz requested changes

2022-07-19 13:18 UTC, backmeupplz commented on src/middlewares/authorAccess.ts
> +    return ctx.throw(notAcceptable())
Факт существования сообщения — это все еще слив информации. Возвращай `notFound` :)

2022-07-19 13:18 UTC, backmeupplz commented on src/middlewares/authorAccess.ts
> +import { Context, Next } from 'koa'
Один middleware называется `authMiddleware`, другой — `authorAccess`. Постарайся назвать их похоже, consistency is the key

2022-07-19 13:18 UTC, backmeupplz commented on src/middlewares/authMiddleware.ts
> +    throw new Error('You are not authorized')
Давай использовать `@hapi/boom`

2022-07-19 13:46 UTC, backmeupplz requested changes

2022-07-19 13:46 UTC, backmeupplz commented on src/middlewares/authMiddleware.ts
> +import { Context, Next } from 'koa'
Нет смысла писать `Middleware` в названии файла в папке `middlewares`

2022-07-19 13:46 UTC, backmeupplz commented on src/middlewares/authorMiddleware.ts
> +import { Context, Next } from 'koa'
Все-таки, мы тут делаем `checkAuthor`

2022-07-19 13:46 UTC, backmeupplz commented on src/middlewares/authorMiddleware.ts
> +    return ctx.throw(notFound())
Ошибка отличается от той, что кидаешь на `L9`, а значит, можно понять, когда есть сообщение

2022-08-02 18:51 UTC, closed without merging