Create CRUD for user messages
Borodutch/backend-starter pull request #110
Opened 2022-05-26 15:57 UTC by EdisonsLamp

2022-05-26 21:15 UTC, backmeupplz requested changes

2022-05-26 21:15 UTC, backmeupplz commented on .env.sample
> -MONGO=mongodb://localhost:27017/test
Этот файл не нужно удалять

2022-05-26 21:15 UTC, backmeupplz commented on src/controllers/messageCrud.ts
> +import { Message } from "@/interface/messageInterface";
Включи у себя `format on save`, тебе не нужны `;`

2022-05-26 21:15 UTC, backmeupplz commented on src/controllers/messageCrud.ts
> +import { Message } from "@/interface/messageInterface";
Посмотри на уже существующий контроллер в папке и сделай похоже

2022-05-26 21:15 UTC, backmeupplz commented on src/helpers/runApp.ts
>  import { bootstrapControllers } from 'amala'
В этом файле не должно быть изменений

2022-05-26 21:15 UTC, backmeupplz commented on src/interface/messageInterface.ts
> +export interface Message {
Тебе не нужна папка `interface`

2022-05-26 21:15 UTC, backmeupplz commented on src/models/messageModel.ts
> +import * as mongoose from "mongoose";
Посмотри на другой файл в `models` и сделай похоже

2022-05-26 21:15 UTC, backmeupplz commented on src/routers/messageRouterCrud.ts
> +import * as messageCrud from "@/controllers/messageCrud"
Тебе не нужна папка `routers`

2022-06-01 14:50 UTC, backmeupplz requested changes

2022-06-01 14:50 UTC, backmeupplz commented on .vscode/settings.json
>      "javascriptreact",
В этом файле не должно быть изменений

2022-06-01 14:51 UTC, backmeupplz requested changes

2022-06-01 14:51 UTC, backmeupplz commented on src/helpers/runApp.ts
>    app.use(bodyParser())
В этом файле не должно быть изменений

2022-06-01 14:51 UTC, backmeupplz commented on src/models/messageModel.ts
> +    title!: string
Тебе достаточно иметь `text` и `author` в сообщении

2022-06-01 14:51 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +        try {
Тебе не нужны `try/catch`

2022-06-01 14:51 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +import * as crudService from './messageCrud'
Используй модульные импорты

2022-06-01 16:03 UTC, EdisonsLamp commented on src/controllers/messageRouterCrud.ts
> +        try {
А как можно будет отловить ошибку не используя try/catch?

2022-06-01 16:45 UTC, backmeupplz requested changes

2022-06-01 16:45 UTC, backmeupplz commented on src/models/Message.ts
> +  @prop({ required: true })
Почитай про `index` и `ref` у `typegoose`

2022-06-01 16:45 UTC, backmeupplz commented on src/controllers/messageCrud.ts
> +import { MessageModel } from '@/models/Message'
Тебе не нужен этот файл

2022-06-01 16:45 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +    return await getAllMessages()
Почитай про `return await`, про то, как `async/await` связаны с `promises` и почему тут не нужен `return await`

2022-06-01 16:45 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +    return result
Не создавай лишние переменные, просто возвращай сразу вызов функции

2022-06-01 16:45 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +  async createMessage(@Body({ required: true }) ctx: Context) {
Посмотри, как сделан тип и валидация `Body` в другом контроллере. Почитай, что такое `Context`.

2022-06-01 16:45 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +  @Put('/delete')
Разный тип (`put`, `delete`, `get`) могут быть на одном и том же пути

2022-06-08 14:15 UTC, backmeupplz requested changes

2022-06-08 14:15 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +  @Get('/all')
Можно сделать `/`

2022-06-08 14:15 UTC, backmeupplz commented on src/models/Message.ts
> +export async function getMessageList() {
Делай это прямо в контроллере сообщений, тебе не нужны лишние функции тут

2022-06-08 14:15 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +  async createMessage(@Body({ required: true }) message: any) {
Никогда не используй `any`, только если крайне необходимо. Тут не должен быть `any`

2022-06-09 15:54 UTC, backmeupplz requested changes

2022-06-09 15:54 UTC, backmeupplz commented on src/validators/Message.ts
> +  _id!: string
Тебе не нужно передавать тут `_id`

2022-06-09 15:54 UTC, backmeupplz commented on src/validators/Message.ts
> +  author!: {}
Автор добавляется внутри контроллера, он не передается в реквесте

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +    const allMessages = await MessageModel.find()
Юзер должен видеть только свои сообщения

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +      .populate('author')
Заполнять автора тоже не нужно

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +    return allMessages
А можно еще этот метод контроллера сделать в одну строку

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +class MessageController {
Файлы и классы, которые экспортишь, должны называться одинаково

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +    const newMessage = new MessageModel(message)
Не передавай что угодно в конструктор сообщения. Сделай destruct параметров функции

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +  async createMessage(@Body({ required: true }) message: Message) {
Может, это валидатор `CreateMessage`?

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +    await newMessage.save()
Эту функцию можно написать в одну строку

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +  async updateMessage(@Body({ required: true }) message: Message) {
Может, валидатор должен быть другим, отличным от создания сообщения?

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +  @Put('/')
Давай добавим сюда `/:id`

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +  async deleteMessage(@Params('id') id: string) {
Надо добавить валидатор

2022-06-09 15:54 UTC, backmeupplz commented on src/controllers/messageRouterCrud.ts
> +    await MessageModel.deleteOne({ _id: id })
Как насчет вернуть результат?

2022-07-03 15:46 UTC, backmeupplz requested changes

2022-07-03 15:46 UTC, backmeupplz commented on src/validators/Message.ts
> +  text!: string
Выглядит точно так же, как `CreateMessage`. Может, нужен только один класс?

2022-07-03 15:46 UTC, backmeupplz commented on src/validators/Login.ts
> +export class Token {
Этот класс тебе не нужен

2022-07-03 15:46 UTC, backmeupplz commented on src/controllers/login.ts
> +    const user = await findOrCreateUser({ name, email })
Не забудь сделать `strippedAndFilled`

2022-07-03 15:46 UTC, backmeupplz commented on src/controllers/Message.ts
> +  async getMessages(@Header() { token }: Token) {
Давай сделаем `middleware`, которая будет проверять токен, находить пользователя и закидывать его в `ctx.state.user` — тогда сможешь использовать `@CurrentUser`! :)

2022-07-03 15:46 UTC, backmeupplz commented on src/controllers/Message.ts
> +    const updatedMessage = await MessageModel.findOneAndUpdate(
Давай подумаем о приватности. Пользователь не должен иметь доступ к чужим сообщениям

2022-08-01 20:15 UTC, backmeupplz requested changes

2022-08-01 20:15 UTC, backmeupplz commented on src/validators/Message.ts
> +export class IdMessage {
Только `Message`? Может, просто `Id`? Если так, то может вынести в отдельный файл?

2022-08-01 20:15 UTC, backmeupplz commented on src/validators/Message.ts
> +  @IsString()
А есть еще `IsMongoId`

2022-08-01 20:15 UTC, backmeupplz commented on src/validators/Login.ts
> +export class Login {
Используй default export

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/login.ts
> +    return user.strippedAndFilled()
Найди отличия с другими использованиями этой функции.

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/login.ts
> +  async login(@Body({ required: true }) { name, email }: Login) {
Просто `login`?

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/login.ts
> +  @Post('/test')
Что за `/test`? Может, есть название лучше?

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/login.ts
> +import { Body, Controller, Ctx, Post, Flow } from 'amala'
Точно нужен `Flow`? Тебе VSC не подсвечивает ошибки?

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/auth.ts
> +  await next()
Почему не сделать просто `return next()`? Почитай про promises и async/await

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/auth.ts
> +  ctx.state.user = await UserModel.findOne({
Как насчет валидировать `token`?

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/auth.ts
> +export default async function auth(ctx: any, next: Function) {
Можно не давать имя функции, которую дефолтно экспортишь

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/auth.ts
> +export default async function auth(ctx: any, next: Function) {
Никогда не используй `any`

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/auth.ts
> +export default async function auth(ctx: any, next: Function) {
`Function` — это неверный тип

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/isAuthor.ts
> +export default async function isAuthor(ctx: any, next: Function) {
`auth` и `isAuthor`. Звучит как-то по-разному. Может, называть миддлвари похоже? Глаголом там или существительным?

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/isAuthor.ts
> +export default async function isAuthor(ctx: any, next: Function) {
`any` и `Function` — неверные типы

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/isAuthor.ts
> +  const message = await MessageModel.findById(ctx.params.id)
А если не найдено?

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/isAuthor.ts
> +    ctx.throw(403, 'Forbidden')
Может, сделать `return`?

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/isAuthor.ts
> +    ctx.throw(403, 'Forbidden')
Слив информации, что сообщение существует — это все еще слив. Человек должен получать 404, если это не его сообщение

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/isAuthor.ts
> +    ctx.throw(403, 'Forbidden')
Писать `Forbidden` бессмысленно, это и есть 403

2022-08-01 20:15 UTC, backmeupplz commented on src/middleware/isAuthor.ts
> +  const currentUserId = ctx.state.user._id.toString()
А есть еще `.id()`. Посмотри отличия

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +  async getMessages(@CurrentUser() user: any) {
Не используй `any`

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +  async getMessages(@CurrentUser() user: any) {
Если назовешь `author` этот аргумент, то сможешь сделать ниже просто `{ author }`

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +    await new MessageModel({ text, author }).save()
Может, `return`, вместо `await`?

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +    @CurrentUser() author: {},
Что это за тип такой `{}`? :)

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +    const updateMessage = await MessageModel.findOneAndUpdate(
А прикольно было бы иметь сообщение в `ctx.state.message` и использовать `@State`, да?

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +    return updateMessage
Так можно сразу делать `return` в одну строку

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +      { text: text },
А почему не просто `{ text }`?

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +      { returnDocument: 'after' }
Это разве не дефолтная опция? Ее можно не вписывать

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +    const deleteMessage = await MessageModel.findByIdAndDelete({ _id: id })
А можно и одной строкой все сделать

2022-08-01 20:15 UTC, backmeupplz commented on src/controllers/Message.ts
> +    const deleteMessage = await MessageModel.findByIdAndDelete({ _id: id })
`findById` принимает просто `id`

2022-08-13 14:33 UTC, backmeupplz requested changes

2022-08-13 14:33 UTC, backmeupplz commented on src/validators/Login.ts
> +  email?: string
Может, `!`?

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/auth.ts
> +export default async function (ctx: Context, next: () => Promise<void>) {
Тебе нужен правильный тип `Next`

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/updateMessage.ts
> +import MessageModel from '@/models/Message'
Может, это `attachMessage`?

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/auth.ts
> +import { Context } from 'koa'
Называй файлы одинаково, тут по логике должен быть у тебя глагол — `authenticate`

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/auth.ts
> +  return ctx.throw(400)
Используй `@hapi/boom`

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/auth.ts
> +    ctx.state.user = await UserModel.findById(id)
Что, если пользователь не найден?

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/auth.ts
> +  if (typeof token === 'string') {
Fail first — сначала проверь, что токен не строка — и кинь ошибку, потом продолжай, как обычно

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/accessMessage.ts
> +    return next()
Не делай else/return

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/accessMessage.ts
> +export default async function (ctx: Context, next: () => Promise<void>) {
Используй правильный тип `Next`

2022-08-13 14:33 UTC, backmeupplz commented on src/middleware/accessMessage.ts
> +    return ctx.throw(404, 'page not found')
Используй `@hapi/boom`

2022-08-13 14:33 UTC, backmeupplz commented on src/validators/Login.ts
> +import { IsString, IsEmail } from 'amala'
Может, назвать файл `EmailLogin`?

2022-08-13 14:33 UTC, backmeupplz commented on src/controllers/login.ts
> +  @Post('/sign')
Что за `/sign`? Что ты подписываешь?

2022-08-13 14:33 UTC, backmeupplz commented on src/controllers/Message.ts
> +    @State('message') message: ID
`@State` не нужно валидировать

2022-08-13 14:33 UTC, backmeupplz commented on src/controllers/Message.ts
> +  @Flow([accessMessage, updateMessage])
Точно нужно и то, и то?

2022-08-17 13:57 UTC, backmeupplz requested changes

2022-08-17 13:57 UTC, backmeupplz commented on src/validators/ID.ts
> +import { IsMongoId } from 'amala'
Может, `MongoId`?

2022-08-17 13:57 UTC, backmeupplz commented on src/validators/Message.ts
> +export default class Message {
Может, `MessageText`?

2022-08-17 13:57 UTC, backmeupplz commented on src/validators/Message.ts
> +import { IsMongoId, IsString } from 'amala'
У кого-то тут VSC не подсвечивает ошибку или кто-то не запускает `yarn lint`? :)

2022-08-17 13:57 UTC, backmeupplz commented on src/controllers/Message.ts
> +    return new MessageModel({ text, author }).save()
Может, использовать `create`?

2022-08-17 13:57 UTC, backmeupplz commented on src/middleware/authenticate.ts
> +    return ctx.throw(new Boom(badRequest('invalid token')))
Не нужно делать `new Boom`

2022-08-17 13:57 UTC, backmeupplz commented on src/middleware/authenticate.ts
> +  const { id } = verify(token)
`verify` может кинуть ошибку, оберни в `try/catch` и кинь правильную ошибку в `catch`

2022-08-17 13:57 UTC, backmeupplz commented on src/middleware/authenticate.ts
> +  const user = await UserModel.findById(id)
Ищи по `token`

2022-08-17 13:57 UTC, backmeupplz commented on src/middleware/authenticate.ts
> +  ctx.state = { user }
Не перезаписывай *весь* `state`, только `ctx.state.user`

2022-08-17 13:57 UTC, backmeupplz commented on src/middleware/accessMessage.ts
> +  const message = await MessageModel.findById(ctx.params.id)
А почему бы прямо тут не закинуть сообщение в `ctx.state.message`?

2022-08-17 13:57 UTC, backmeupplz commented on src/middleware/accessMessage.ts
> +  const message = await MessageModel.findById(ctx.params.id)
Что, если `message` не найден?

2022-08-17 13:57 UTC, backmeupplz commented on src/middleware/accessMessage.ts
> +    return ctx.throw(new Boom(notFound('Page not found')))
Этот `page`, он сейчас с нами в одной комнате? :)

2022-08-17 19:55 UTC, backmeupplz requested changes

2022-08-17 19:55 UTC, backmeupplz commented on src/controllers/Message.ts
> +      { _id: message.id },
Можешь упростить до просто `.findOneAndUpdate(message, <...>`

2022-08-17 19:55 UTC, backmeupplz commented on src/controllers/Message.ts
> +  @Flow(accessMessage)
`attachMessage` лучше звучит тут

2022-10-20 15:01 UTC, closed without merging