CRUD_APP
Borodutch/backend-starter pull request #114
Opened 2022-06-18 11:54 UTC by TSENTSEUS

Fixed previous remarks

2022-06-19 18:47 UTC, backmeupplz requested changes

2022-06-19 18:47 UTC, backmeupplz commented on .env.sample
> -MONGO=mongodb://localhost:27017/test
Этот файл не нужно удалять

2022-06-19 18:47 UTC, backmeupplz commented on src/models/messageModel.ts
> +  message?: string
Может, `text`?

2022-06-19 18:47 UTC, backmeupplz commented on src/models/messageModel.ts
> +  message?: string
`required: true` или `?`?

2022-06-19 18:47 UTC, backmeupplz commented on src/models/messageModel.ts
> +  message?: string
Почитай про `index` и подумай, где он не нужен

2022-06-19 18:47 UTC, backmeupplz commented on src/controllers/homePage.ts
> +  PostMessage(@Body({ required: true }) body: any) {
Добавь валидаторы и не используй `any`

2022-06-19 18:47 UTC, backmeupplz commented on src/controllers/homePage.ts
> +      user: body.user,
Создай новый метод в login контроллере, который принимает только email — и возвращает зарегистрированного пользователя (пароль не нужен). Используй токен этого юзера в `request headers`, валидируй этот токен через middleware — и используй этот middleware тут. Можешь еще юзера добавить в `ctx.state.user` — и использовать `@CurrentUser`

2022-07-08 15:22 UTC, backmeupplz commented on src/controllers/homePage.ts
> +import {
Это же контроллер `message`, а не `homePage`

2022-07-08 15:23 UTC, backmeupplz commented on src/models/messageModel.ts
> +  author?: Ref<User>
Хм, это все-таки `required`, или `?`?

2022-07-08 15:24 UTC, backmeupplz commented on src/controllers/homePage.ts
> +  getMessages() {
Нужно получать только свои сообщения

2022-07-08 15:24 UTC, backmeupplz commented on src/controllers/homePage.ts
> +  deleteMessage(@Params('id') id: any) {
Пользователь должен иметь доступ только к своим сообщениям, все остальное должно возвращать `404`

2022-07-08 20:46 UTC, TSENTSEUS commented on src/models/messageModel.ts
> +  author?: Ref<User>
required

2022-07-09 14:51 UTC, backmeupplz requested changes

2022-07-09 14:51 UTC, backmeupplz commented on src/controllers/messageController.ts
> +    console.log(message)
Не пушь в PR ненужные `console.log`

2022-07-11 17:54 UTC, closed without merging