CRUD messages
Borodutch/backend-starter pull request #121
Opened 2022-09-01 08:54 UTC by twiksokyan

Добавление CRUD-сообщений пользователями

2022-09-01 13:30 UTC, backmeupplz requested changes

2022-09-01 13:30 UTC, backmeupplz commented on src/models/MessageModel.ts
> +  messageAuthor!: Ref<User>
Это и так модель под названием `Message` :) нет смысла писать `message` в названиях полей. Достаточно просто назвать это поле `author`

2022-09-01 13:30 UTC, backmeupplz commented on src/models/MessageModel.ts
> +import { Ref, getModelForClass, modelOptions, prop } from '@typegoose/typegoose'
Этот файл в папке `models`, нет смысла дублировать слово `Model` в названии файла

2022-09-01 13:30 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +    return ctx.throw(badRequest('user not found'))
Неверное описание ошибки

2022-09-01 13:30 UTC, backmeupplz commented on src/middlewares/checkMessage.ts
> +  const authorId = message.messageAuthor?.toString()
Зачем тут `?`? Это поле `required`

2022-09-01 13:30 UTC, backmeupplz commented on src/controllers/login.ts
> +    @Ctx() ctx: Context,
`ctx` не используется

2022-09-01 13:30 UTC, backmeupplz commented on src/controllers/login.ts
> +    @Body({ required: true }) body: EmailLogin
Сделай `destruction` параметра `body`

2022-09-01 13:30 UTC, backmeupplz commented on src/controllers/message.ts
> +    return new MessageModel({ text, messageAuthor }).save()
Попробуй `MessageModel.create`

2022-09-01 13:31 UTC, backmeupplz requested changes

2022-09-01 13:31 UTC, backmeupplz commented on src/controllers/message.ts
> +  deleteMessage(@State('message') message: Context) {
Это неверный тип параметра

2022-09-01 15:00 UTC, twiksokyan commented on src/models/MessageModel.ts
> +  messageAuthor!: Ref<User>
исправил

2022-09-01 15:01 UTC, twiksokyan commented on src/models/MessageModel.ts
> +import { Ref, getModelForClass, modelOptions, prop } from '@typegoose/typegoose'
исправил

2022-09-01 15:01 UTC, twiksokyan commented on src/controllers/login.ts
> +    @Ctx() ctx: Context,
поправил

2022-09-01 15:01 UTC, twiksokyan commented on src/controllers/login.ts
> +    @Body({ required: true }) body: EmailLogin
сделал

2022-09-01 15:01 UTC, twiksokyan commented on src/controllers/message.ts
> +    return new MessageModel({ text, messageAuthor }).save()
сделал

2022-09-01 15:07 UTC, backmeupplz requested changes

2022-09-01 15:07 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await MessageModel.create({ text, author })
Почитай про `promises`, про `async/await`, про `return await` и подумай, нужен ли он тут

2022-09-02 13:36 UTC, twiksokyan commented on src/controllers/message.ts
> +  deleteMessage(@State('message') message: Context) {
исправил

2022-09-02 13:40 UTC, twiksokyan commented on src/controllers/message.ts
> +    return await MessageModel.create({ text, author })
Прочитал. Убрал async/await:)

2022-10-03 14:11 UTC, backmeupplz requested changes

2022-10-03 14:11 UTC, backmeupplz commented on src/controllers/message.ts
> +    @Body({ required: true }) { text }: { text: string }
Куда-то пропала валидация!

2022-10-03 14:11 UTC, backmeupplz commented on src/controllers/message.ts
> +    @Body({ required: true }) { text }: { text: string },
Где валидация?

2022-10-03 14:11 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('testing POST', async () => {
Тут нужно проверять не то, какой ответ тебе приходит — а то, что в базе данных происходит

2022-10-03 14:11 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('testing GET', async () => {
`it` тут не просто так стоит :) `it('returns message correctly'...`

2022-10-03 19:49 UTC, twiksokyan commented on src/controllers/message.ts
> +    @Body({ required: true }) { text }: { text: string }
поправил

2022-10-03 19:49 UTC, twiksokyan commented on src/controllers/message.ts
> +    @Body({ required: true }) { text }: { text: string },
поправил

2022-10-03 19:49 UTC, twiksokyan commented on src/__tests__/message.ts
> +  it('testing POST', async () => {
поменял на проверку наличия нового документа в БД

2022-10-03 19:49 UTC, twiksokyan commented on src/__tests__/message.ts
> +  it('testing GET', async () => {
поменял названия всех тест-кейсов

2022-10-03 19:50 UTC, twiksokyan commented on src/__tests__/message.ts
> +
добавил 2 теста

2022-10-03 19:59 UTC, backmeupplz requested changes

2022-10-03 19:59 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(newMessage).not.toBeNull()
Тебя точно устраивает, что сообщение просто создано? Точно не хочешь проверить его поля?

2022-10-03 19:59 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(response.body.text).toBe(postText.text)
Не надейся на то, что `response` вернет правильный ответ. Считай, что `response.body` — это `{ status: 'ok' }`

2022-10-03 19:59 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('checks the appearance of new message in DB', async () => {
`adds the new message to the DB`

2022-10-03 19:59 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('checks update of existing message', async () => {
проверяешь ты — а тест `updates the message correctly`

2022-10-03 19:59 UTC, backmeupplz commented on src/__tests__/message.ts
> +  const putText = { text: 'da, eto ya!' }
Используешь это во многих местах или только в одном? Точно нужно делать переменную на это уровне?

2022-10-03 21:15 UTC, twiksokyan commented on src/__tests__/message.ts
> +  const putText = { text: 'da, eto ya!' }
пересмотрел использование переменных, поправил

2022-10-03 21:15 UTC, twiksokyan commented on src/__tests__/message.ts
> +    expect(newMessage).not.toBeNull()
добавил проверки полей

2022-10-03 22:15 UTC, backmeupplz requested changes

2022-10-03 22:15 UTC, backmeupplz commented on src/controllers/message.ts
> +@Controller('/crud')
Это же `message` контроллер, какой `crud`?

2022-10-03 22:15 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('makes post with unregistered token', async () => {
Нужно писать не то, что делает тест, а то, что проверяет. Ты проверяешь не посылание метода `post`, ты проверяешь, что `it rejects adding a message with an invalid token`

2022-10-03 22:15 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('makes post with unregistered token', async () => {
Только в `POST /messages` может такая ошибка выпасть?

2022-10-03 22:15 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(typeof newMessage?.text).toBe('string')
Тебе не нужно это проверять

2022-10-03 22:15 UTC, backmeupplz commented on src/__tests__/message.ts
> +    const newMessage = await MessageModel.findById(newMessageId)
Смысла создавать переменную `newMessageId` нет. Как и смысла называть `message` переменной `newMessage`

2022-10-03 22:16 UTC, closed without merging