CRUD "сообщений"
Borodutch/backend-starter pull request #127
Opened 2022-11-14 12:13 UTC by untitledrev

CRUD "сообщений"

2022-11-15 03:36 UTC, backmeupplz requested changes

2022-11-15 03:36 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Post('/create')
Используй разные методы — `@Post`, `@Get`, `@Put`, тогда сможешь везде поставить один путь `/`

2022-11-15 03:36 UTC, backmeupplz commented on src/models/Message.ts
> +export async function createMessage(MessageOptions: {
Тебе не нужны методы ниже, просто используй `MessageModel` прямо в функциях контроллера

2022-11-15 03:36 UTC, backmeupplz commented on src/models/Message.ts
> +  strippedAndFilled(
Тебе в этом случае не нужен `strippedAndFilled`

2022-11-15 03:36 UTC, backmeupplz commented on src/models/Message.ts
> +  id_user?: string
1. Это TypeScript, тут только camel case для переменных
2. Здесь должен быть `ref: User`
3. Назвать это можно `author`

2022-11-15 03:36 UTC, backmeupplz commented on src/models/Message.ts
> +  text?: string
Сообщение без текста? Не нужно такого :) сделай `required: true`

2022-11-15 03:36 UTC, backmeupplz commented on src/controllers/message.ts
> +    return '{"messege" : "successfully"}'
Ты либо строки возвращай, либо JSON — но не JSON, который ты вручную написал в строке

2022-11-15 03:36 UTC, backmeupplz commented on src/controllers/message.ts
> +    const id_user = await authenticationUser({ token })
Это нужно делать через `middleware`, можешь даже внутри этой миддлвари пользователя полученного поставить в `ctx.state.user` — и использовать `@CurrentUser`

2022-11-15 03:36 UTC, backmeupplz commented on src/validators/MessageGetOrDelet.ts
> +  token!: string
Передавай `token` в `ctx.request.headers`

2022-11-15 16:30 UTC, backmeupplz requested changes

2022-11-15 16:30 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await MessageModel.create({ text, author })
Почитай про `return await`, он не нужен тут :)

2022-11-19 19:59 UTC, backmeupplz requested changes

2022-11-19 19:59 UTC, backmeupplz commented on src/validators/MessageText.ts
> +export default class Message {
Это `Message` или `MessageText`?

2022-11-19 19:59 UTC, backmeupplz commented on src/middleware/verifyUser.ts
> +  if (ctx.state.user.id != ctx.state.message.author) {
Это что за покемон в TypeScript? Не знаю, как это прошло линтер, но делать небезопасные проверки на равенство — это неправильно. Тебе тут нужен `!==`. Если типы неверные — так исправь типы :)

2022-11-19 19:59 UTC, backmeupplz commented on src/middleware/authenticate.ts
> +export default async function authenticationUser(ctx: Context, next: Next) {
`authenticate` или `authenticationUser`? Определись

2022-11-19 19:59 UTC, backmeupplz commented on src/middleware/authenticate.ts
> +    verify(token)
Советую сначала верифицировать, а потом идти в бд

2022-11-19 19:59 UTC, backmeupplz commented on src/controllers/message.ts
> +    @Body({ required: true }) { text }: Message,
Здесь нужен валидатор. И да, нужно написать тест, который триггерит ошибку валидатора.

2022-11-19 19:59 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Get('/:id')
Давай еще сделаем получение всех сообщений пользователя

2022-11-19 19:59 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Flow(verifyUser)
юзера верифицируешь или автора?

2022-11-19 19:59 UTC, backmeupplz commented on src/controllers/message.ts
> +    return MessageModel.findById(message)
А чего сразу не вернуть результат `L42`? Два запроса в БД, вместо одного — это бессмыслица

2022-11-19 19:59 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('metod message Create', async () => {
`it metod message Create` — это какой-то сломанный английский. `it('creates message successfully'...`

2022-11-19 19:59 UTC, backmeupplz commented on src/__tests__/message.ts
> +    const messageInfo = JSON.parse(messageInfoRes.text)
Что это за хаки?

2022-11-19 19:59 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(Boolean(messageInfo)).toBe(true)
Как насчет проверить БД, а не просто ответ сервера?

2022-11-27 13:40 UTC, untitledrev commented on src/controllers/message.ts
> +    return MessageModel.findById(message)
Он findByIdAndUpdate возвращает результат не именную модель. Что бы отдать измененную надо запросить еще раз.

2022-11-27 13:48 UTC, untitledrev commented on src/__tests__/message.ts
> +    const messageInfo = JSON.parse(messageInfoRes.text)
Разбираем ответ  из json в массив. Что бы можно было каждую переменную ответа проверить отдельно на определенное соответствие.

2022-11-27 17:14 UTC, untitledrev commented on src/__tests__/message.ts
> +    expect(Boolean(messageInfo)).toBe(true)
А что подразумевается под проверкой БД?

2022-11-27 19:16 UTC, backmeupplz requested changes

2022-11-27 19:16 UTC, backmeupplz commented on src/models/Message.ts
> +  @prop({ required: true, ref: () => User })
Почитай про аргумент `index`

2022-11-27 19:16 UTC, backmeupplz commented on src/validators/MessageText.ts
> +export default class MessageText {
Кстати, можно и не давать имя, если у тебя `export default class` :)

2022-11-27 19:16 UTC, backmeupplz commented on src/middleware/verifyAuthor.ts
> +  if (ctx.state.user.id !== String(ctx.state.message.author)) {
Лучше использовать `...author.toString()`

2022-11-27 19:16 UTC, backmeupplz commented on src/middleware/authenticate.ts
> +export default async function authenticate(ctx: Context, next: Next) {
Можно и не давать дефолтному экспорту имя

2022-11-27 19:16 UTC, backmeupplz commented on src/controllers/message.ts
> +    return MessageModel.findById(message)
Почитай про аргументы, которые `findByIdAndUpdate` принимает и сделай только один запрос :)

2022-11-27 19:16 UTC, backmeupplz commented on src/controllers/message.ts
> +  getMessage(@CurrentUser() author: User) {
Только одно сообщение?

2022-11-27 19:16 UTC, backmeupplz commented on src/controllers/message.ts
> +    return MessageModel.findById(message)
Зачем еще раз искать сообщение? Просто верни `message`

2022-11-27 19:16 UTC, backmeupplz commented on src/controllers/message.ts
> +export default class MessageController {
Можно и не называть дефолтный экспорт

2022-11-27 19:16 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(Boolean(messageInfo)).toBe(true)
Представь, что все твои методы возвращают `{ success: true }` — и больше ничего. Как верифицировать в тесте, что сообщение создано\удалено\изменено?

2022-11-27 19:16 UTC, backmeupplz commented on src/__tests__/message.ts
> +    const messageInfo = JSON.parse(messageInfoRes.text)
`messageInfoRes` не строка

2022-12-03 15:14 UTC, backmeupplz requested changes

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +      ...baseUserTelegramm,
Зачем этот хак? :) Передай просто `baseUserTelegramm`, а не `{ ...baseUserTelegramm }`. Ну и опечатку поправь

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +  let userCreate
Про типы не забывай

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +  let message_id: string
В TypeScript мы не используем snake_case

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    token = !userCreate.token ? '' : userCreate.token
Что это такое? У тебя может не быть `userCreate.token`? И если нет, то ты его ставишь `''`? Пустая строка — чаще всего не выход. Если у тебя "либо строка, либо ничего" — то правильно делать "ничего" (`undefined`), а не "пустая строка" (`""`)

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    userCreate = await UserModel.create({
`userCreate` звучит как функция, а не как переменная. Это глагол, а не существительное.

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    message_id = String(message._id)
Что это за хаки с `String(...)`? Убирай. Есть поле `id`, которое и является `_id.toString()`

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    user_id = String(userCreate.id)
`.id` — это уже `string`

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +      .send(messageTest)
То есть ты дважды создаешь одно и то же сообщение? Сначала в `beforeEach`, потом тут? Может, не нужно в `beforeEach` создавать сообщение?

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +      messageTest,
Какое из двух сообщений найдет этот запрос? И верное ли это сообщение? Реквест возвращает тебе `id` сообщения — по нему и ищи

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +      .send(messageTest)
Всем ли методам нужно созданное сообщение? Пиши **меньше** кода, не больше.

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(Boolean(messageInfo)).toBe(true)
Что это за хак с `Boolean(...)`? Ты проверяешь, есть ли сообщение? Проверяй на `not undefined` или `not null`

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(String(!messageInfo ? null : messageInfo.author)).toBe(user_id)
Прекращай кастить типы через `String(...)`

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('validation error successfully', async () => {
`it validation error successfully` — сломанный английский, исправляй

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +  it('validation error successfully', async () => {
Ты проверяешь все валидации или одну определенную валидацию? Называй тесты правильно.

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +      .get('/message/' + message_id)
Используй string templates, а не `+`

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(Boolean(messageInfo)).toBe(true)
Прекращай кастовать через `Boolean(...)`. Если хочешь кастануть в `boolean`, то используй `!!variable`. Но, скорее всего, тебе не нужно кастовать в `boolean`

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(Boolean(messageInfo)).toBe(true)
Это всегда будет `true`, ведь если у тебя нет сообщений, то вернется `[]`

2022-12-03 15:14 UTC, backmeupplz commented on src/__tests__/message.ts
> +    expect(!messageInfo ? null : messageInfo.id).toBe(message_id)
Что это за хаки с ternary operators? Убирай их

2022-12-03 21:19 UTC, untitledrev commented on src/__tests__/message.ts
> +      .send(messageTest)
В тести на получение всех сообщений пользователя(get all author messages successfully), нужно хотя бы 2.  И как раз используется то которое создано в `beforeEach`

2023-11-06 18:39 UTC, closed without merging