best CRUD
Borodutch/backend-starter pull request #129
Opened 2022-11-18 15:48 UTC by redsomber

- creates local users
- adds, edits, deletes and displays messages by token

2022-11-18 16:04 UTC, backmeupplz requested changes

2022-11-18 16:04 UTC, backmeupplz commented on src/validators/newUser.ts
> +export default class newUser {
Старых юзеров не проверяем?

2022-11-18 16:04 UTC, backmeupplz commented on src/middlewares/getMsgById.ts
> +  //   console.log(message)
Не пушь закомментированный код в PR

2022-11-18 16:04 UTC, backmeupplz commented on src/controllers/MsgController.ts
> +
Может, стоит удалить лишние пустые строки?

2022-11-18 16:04 UTC, backmeupplz commented on src/controllers/MsgController.ts
> +@Controller('/msg')
Зачем сокращать что-то просто так? Почему не `/messages`?

2022-11-18 20:29 UTC, backmeupplz requested changes

2022-11-18 20:29 UTC, backmeupplz commented on .editorconfig
> +root = true
Этот файл не нужен

2022-11-18 20:29 UTC, backmeupplz commented on src/validators/UserValidator.ts
> +import { IsString } from 'amala'
Нет смысла называть файл `validators/UserValidator`, он уже в папке `validators`. Ну и название класса должно быть таким же, как и название файла

2022-11-18 20:29 UTC, backmeupplz commented on src/validators/UserValidator.ts
> +  email?: string
Его может не быть?

2022-11-18 20:29 UTC, backmeupplz commented on src/validators/MsgValidator.ts
> +export default class MsgValidator {
Нет смысла сокращать `Message` до `Msg` — ничего не выигрываешь, а читать сложнее.

2022-11-18 20:29 UTC, backmeupplz commented on src/validators/MsgState.ts
> +  message!: Message
Это не валидатор без валидации. Скорее всего, этот файл тебе не нужен.

2022-11-18 20:29 UTC, backmeupplz commented on src/models/MsgModel.ts
> +  _id!: ObjectId
Это поле есть у всех объектов в MongoDB, тебе не нужно лишний раз его объявлять

2022-11-18 20:29 UTC, backmeupplz commented on src/models/MsgModel.ts
> +  text?: string
Либо `required: true`, либо `?`, определись :)

2022-11-18 20:29 UTC, backmeupplz commented on src/models/MsgModel.ts
> +  @prop({ required: true })
Почитай про `index` поле. Ну и если это `ref` — укажи `ref`

2022-11-18 20:29 UTC, backmeupplz commented on src/models/MsgModel.ts
> +export default class Message {
Класс — `Message`, файл — `MsgModel`, как правильно?

2022-11-18 20:29 UTC, backmeupplz commented on src/middlewares/getMsgById.ts
> +  //   console.log(id)
Не пушь закомментированный код в PR — это дурной тон

2022-11-18 20:29 UTC, backmeupplz commented on src/middlewares/getMsgById.ts
> +export default async function getMsgById(ctx: Context, next: Next) {
`getMsgById` возвращает результат `next()`, а не сообщение. Может, это не `get message by ID`?

2022-11-18 20:29 UTC, backmeupplz commented on src/middlewares/authUser.ts
> +    throw notFound
Проверь, работает ли это

2022-11-18 20:29 UTC, backmeupplz commented on src/controllers/login.ts
> +  @Post('/new')
А есть `/old`?

2022-11-18 20:29 UTC, backmeupplz commented on src/controllers/login.ts
> +import User from '@/validators/UserValidator'
Это ты юзера валидируешь? Может, `EmailLogin`?

2022-11-19 18:14 UTC, redsomber commented on src/models/MsgModel.ts
> +  @prop({ required: true })
index позволяет ограничить поиск по коллекции сканируя только индексированные элементы ускоряя работу базы данных правильно понял?

2022-11-19 19:50 UTC, backmeupplz requested changes

2022-11-19 19:50 UTC, backmeupplz commented on src/validators/EmailLogin.ts
> +  @IsString()
Есть `IsEmail`

2022-11-19 19:50 UTC, backmeupplz commented on src/models/MessageModel.ts
> +import { Ref, getModelForClass, modelOptions, prop } from '@typegoose/typegoose'
Посмотри, как называется другой файл в этой папке

2022-11-19 19:50 UTC, backmeupplz commented on src/models/MessageModel.ts
> +  text?: string
Либо `required: true`, либо `?` — выбирай

2022-11-19 19:50 UTC, backmeupplz commented on src/middlewares/MessageChecker.ts
> +export default async function MessageChecker(ctx: Context, next: Next) {
это функция, функции называются глаголами и с маленькой буквы

2022-11-19 19:50 UTC, backmeupplz commented on src/middlewares/MessageChecker.ts
> +    return ctx.throw(notFound())
это же `badRequest`

2022-11-19 19:50 UTC, backmeupplz commented on src/controllers/Message.ts
> +    console.log(MessageModel.find({ user }))
Не пушь лишние `console.log` в PR — это дурной тон

2022-11-19 19:50 UTC, backmeupplz commented on src/controllers/Message.ts
> +export default class CRUD {
А как файл называется?

2022-11-19 19:50 UTC, backmeupplz commented on src/models/MessageModel.ts
> +  user!: Ref<User>
давай назовем это поле `author`

2022-11-19 19:50 UTC, backmeupplz commented on src/controllers/Message.ts
> +    return MessageModel.findByIdAndDelete(message.id)
Любой пользователь может удалить сообщение любого другого пользователя?

2022-11-19 19:50 UTC, backmeupplz commented on src/controllers/Message.ts
> +import MessageCheckerId from '@/middlewares/MessageChecker'
У файла одно название — у импортируемой переменной другое. Не надо так.

2022-11-20 17:19 UTC, backmeupplz requested changes

2022-11-20 17:19 UTC, backmeupplz commented on src/middlewares/checkAuthor.ts
> +    return ctx.throw(notFound('not your message'))
Сам факт существования сообщения — это уже слив данных. Ошибка должна быть такой же, как на `L18`

2022-11-20 17:19 UTC, backmeupplz commented on src/middlewares/checkAuthor.ts
> +  } else {
Не делай `return/else`, почитай, почему

2022-11-28 19:02 UTC, backmeupplz requested changes

2022-11-28 19:02 UTC, backmeupplz commented on src/controllers/Messages.ts
> +  getMessage(@CurrentUser() author: DocumentType<User>) {
`getMessage` или `getMessages`?

2022-11-28 19:02 UTC, backmeupplz commented on src/__tests__/messages.ts
> +      const postMessage = await messageModel.findOne(messageText)
Что-то странное, почему ты ищешь сообщение по тексту?

2022-11-28 19:02 UTC, backmeupplz commented on src/__tests__/messages.ts
> +      expect(body._id).toBe(postMessage?.id)
Зачем везде `?`? Просто проверь один раз, есть ли `postMessage`

2022-11-28 19:02 UTC, backmeupplz commented on src/__tests__/messages.ts
> +      expect(body._id).toBe(message.id)
Надо в бд проверять, а не просто ответ проверять

2022-11-30 13:59 UTC, closed without merging