Introducing CRUD for messages + tests
Borodutch/backend-starter pull request #131
Opened 2022-12-15 19:34 UTC by Alamac

- Explain what this PR changes
- in one or more
- bullet points

2022-12-15 21:06 UTC, backmeupplz requested changes

2022-12-15 21:06 UTC, backmeupplz commented on src/middleware/checkAuthorship.ts
> +    ctx.throw(forbidden('User unauthorized to see this message'))
Не сливай информацию о существовании чужого сообщения

2022-12-15 21:06 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await MessageModel.deleteMany({ author: user })
Почитай про promises, их отношение к async/await, а потом про `return await`

2022-12-15 21:06 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await MessageModel.deleteMany({ author: user })
Если назовешь переменную `user` названием `author`, то сможешь короче запись сделать

2022-12-15 21:06 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await MessageModel.deleteOne({ id: message.id })
Можешь даже просто сделать `deleteOne(message)` — подумай, почему. Либо делай `deleteOneById`

2022-12-15 21:06 UTC, backmeupplz commented on src/controllers/message.ts
> +      throw serverUnavailable(
Во-первых, `serverUnavailable` тут не подходит. Во-вторых, убирай `try/catch` из контроллеров. Хочешь ловить ошибки — лови на уровне koa, а не на уровне контроллеров

2022-12-15 21:06 UTC, backmeupplz commented on src/controllers/message.ts
> +    @Body({ required: true }) { text }: DocumentType<MessageData>,
Почитай, что такое `DocumentType`

2022-12-15 21:06 UTC, backmeupplz commented on src/__tests__/message.ts
> +      expect(body.text).toBe('New test message')
Как насчет проверить бд, а не просто ответ сервера?

2022-12-15 21:06 UTC, backmeupplz commented on src/__tests__/message.ts
> +      expect(JSON.stringify(body)).toBe(JSON.stringify(userMessages))
Хаков с `json.stringify` быть не должно

2022-12-15 21:06 UTC, backmeupplz commented on src/__tests__/message.ts
> +        .set('token', userA.token || '')
`||` тут не нужно

2022-12-15 21:06 UTC, backmeupplz commented on src/__tests__/message.ts
> +  describe('DELETE /message/{id}', () => {
Что такое `{id}`?

2022-12-16 00:02 UTC, Alamac commented on src/__tests__/message.ts
> +      expect(JSON.stringify(body)).toBe(JSON.stringify(userMessages))
Из-за того, что в ответе timestamp кастится в строку красивого решения не придумал.

2022-12-16 00:24 UTC, backmeupplz requested changes

2022-12-16 00:24 UTC, backmeupplz commented on src/validators/MessageData.ts
> +export default class MessageData {
Кстати, можешь не называть класс, если это default export

2022-12-16 00:24 UTC, backmeupplz commented on src/middleware/checkAuthorship.ts
> +export default async function checkAuthorship(ctx: Context, next: Next) {
Функции тоже можно не называть, если это default export

2022-12-16 00:24 UTC, backmeupplz commented on src/middleware/checkAuthorship.ts
> +    ctx.throw(notFound('There is no message with this ID'))
Сливать факт того, что сообщение существует — это тоже сливать данные

2022-12-16 00:24 UTC, backmeupplz commented on src/controllers/message.ts
> +      .then((result) => {
Не мешай async/await и then/catch

2022-12-16 00:24 UTC, backmeupplz commented on src/__tests__/message.ts
> +        .set('token', userA.token || '')
Нет. Если `userA.token` пустое — то точно что-то пошло не так

2022-12-16 00:24 UTC, backmeupplz commented on src/__tests__/message.ts
> +      //expect(body.message).toBe(unauthorized('Token is absent').message)
Ну пушь закомментированный код в pull request — это дурной тон

2022-12-16 00:24 UTC, backmeupplz commented on src/__tests__/message.ts
> +        message!._id.toString(),
Что это за `!`? Не используй `!`

2022-12-16 00:24 UTC, backmeupplz commented on src/__tests__/message.ts
> +        message!._id.toString(),
Алсо, почитай, что такое `.id` и что такое `._id` — и в чем разница

2022-12-16 14:54 UTC, backmeupplz requested changes

2022-12-16 14:54 UTC, backmeupplz commented on src/middleware/checkAuthorship.ts
> +    ctx.throw(forbidden())
`forbidden` не стоит использовать, когда сообщение не найдено, правильно использовать `notFound`

2022-12-16 14:54 UTC, backmeupplz commented on src/middleware/authUser.ts
> +    ctx.throw(forbidden('Invalid token'))
У тебя продолжится выполнение функции, надо сделать `return ctx.throw(...)`

2022-12-16 14:54 UTC, backmeupplz commented on src/controllers/message.ts
> +    if (!result) {
Зачем эта проверка? При каком варианте `result` будет пустым? Просто верни результат `save()`

2022-12-16 14:54 UTC, backmeupplz commented on src/__tests__/message.ts
> +    if (userA.token && userB.token) {
То есть, если их нет, то тесты продолжатся? Может, кинуть exception, если их нет? Fail first, продолжай нормальное выполнение функции после

2022-12-16 14:54 UTC, backmeupplz commented on src/__tests__/message.ts
> +      expect(message).resolves
Что за хак с `resolves`?

2022-12-16 14:54 UTC, backmeupplz commented on src/__tests__/message.ts
> +        message?.id.toString(),
Зачем тебе постоянные `?`? Просто проверь `if (!message) throw new Error(...)`

2022-12-16 14:54 UTC, backmeupplz commented on src/__tests__/message.ts
> +      expect(body[0].text).toBe(userMessages[0].text)
А можно это сделать с `for loop`?

2022-12-16 14:54 UTC, backmeupplz commented on src/__tests__/message.ts
> +      expect(body[0].text).toBe(userMessages[0].text)
К тестам тоже нужно применять DRY

2022-12-16 14:54 UTC, backmeupplz commented on src/__tests__/message.ts
> +    await MessageModel.create({ author: userA, text: 'TestB' })
Тебе во всех тестах нужны эти два сообщения?

2022-12-16 18:10 UTC, backmeupplz requested changes

2022-12-16 18:10 UTC, backmeupplz commented on src/middleware/checkAuthorship.ts
> +    ctx.throw(forbidden())
Слив факта существования чужого сообщения — это слив данных. Не надо так.

2022-12-16 18:10 UTC, backmeupplz commented on src/__tests__/message.ts
> +        message.author?.toString(),
У `message` может не быть `author`?

2022-12-16 18:10 UTC, backmeupplz commented on src/__tests__/message.ts
> +        message.id.toString(),
Почитай про разницу между `_id` и `id`

2022-12-16 18:10 UTC, backmeupplz commented on src/__tests__/message.ts
> +    if (userA.token && userB.token) {
Fail first. Сначала проверяй, неверно ли — и кидай exception, потом продолжай, как обычно. Не надо тут делать `if/else`. Один `if` — чтобы нормальный юзкейс не нестить в бесконечных if/else

2022-12-16 19:32 UTC, closed without merging