lesson 3. CRUD for user messages
Borodutch/backend-starter pull request #37
Opened 2021-05-23 14:38 UTC by moody-cookie

Lesson 3. Basic CRUD for user messages.
-- ПУШИС

2021-05-23 14:44 UTC, backmeupplz requested changes

2021-05-23 14:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +@Flow([ authMiddleware ]) // // for Users only
Стоит убрать лишние комментарии

2021-05-23 14:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +@Flow([ authMiddleware ]) // // for Users only
Алсо, тут можно не массив, а просто middleware передавать, вроде как (но это не точно)

2021-05-23 14:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.find()
Почитай про `return await` и почему тут это не нужно

2021-05-23 14:44 UTC, backmeupplz commented on src/middleware/authMiddleware.ts
> +    const token: string = ctx.header.token as string;
Либо кастуй типы через `:`, либо через `as`, не нужно и так, и так делать

2021-05-23 14:44 UTC, backmeupplz commented on src/middleware/authMiddleware.ts
> +import { Context } from 'koa';
Включи у себя prettier и format on save

2021-05-23 14:44 UTC, backmeupplz commented on src/middleware/authMiddleware.ts
> +    await next()
Вместо `await next()` можно сделать `return next()`, посмотри, в чем разница

2021-05-23 14:44 UTC, backmeupplz commented on src/middleware/authMiddleware.ts
> +    await verify(token)
Тут можно еще и прикрепить объект пользователя в `ctx`, чтобы он после использования этой миддлвари везде работал

2021-05-23 14:44 UTC, backmeupplz commented on src/models/message.ts
> +export class Message {
Наверное, нужно еще поле `author: User` сделать, чтобы понимать, кто создал этот месседж

2021-05-23 14:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.find()
Алсо, стоит возвращать только месседжи этого пользователя

2021-05-23 14:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +  async updateMessage(
Надо бы тут проверить, есть ли у пользователя права менять этот месседж (чтобы чужие менять было нельзя)

2021-05-23 14:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +  @Delete('/')
Надо бы тут проверить, есть ли у пользователя права удалять этот месседж (чтобы чужие менять было нельзя)

2021-05-23 14:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return {
Тут достаточно будет вернуть статус `200`

2021-05-24 14:10 UTC, moody-cookie commented on src/controllers/messages.ts
> +@Flow([ authMiddleware ]) // // for Users only
> Алсо, тут можно не массив, а просто middleware передавать, вроде как (но это не точно)

Попытка добавить в @Flow middleware без обёртки в массив заканчивается ошибкой на моменте подключения роутов: 
[Скрин](https://imgur.com/a/WoPKE51)

2021-05-24 14:16 UTC, backmeupplz requested changes

2021-05-24 14:16 UTC, backmeupplz commented on src/models/message.ts
> +  authorId: string
Сделай через User Ref, пожалуйста

2021-05-24 14:16 UTC, backmeupplz commented on src/controllers/messages.ts
> +      authorId: ctx.state.user._id,
Здесь должно быть `author: ctx.state.user,`

2021-05-24 14:16 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const originalMessage = await MessageModel.findOneAndUpdate(
Нужно добавить проверку, чтобы пользователь не смог редактировать чужие сообщения

2021-05-24 14:16 UTC, backmeupplz commented on src/controllers/messages.ts
> +    await MessageModel.deleteOne({ _id: ctx.request.body._id })
Нужно добавить проверку, чтобы пользователь не мог удалять чужие сообщения

2021-06-02 15:10 UTC, closed without merging