Adds CRUD for messages
Borodutch/backend-starter pull request #42
Opened 2021-06-05 13:23 UTC by gluknik

2021-06-05 20:15 UTC, backmeupplz requested changes

2021-06-05 20:15 UTC, backmeupplz commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
Зачем этот файл удалять?

2021-06-05 20:15 UTC, backmeupplz commented on package-lock.json
> +{
Этот файл не нужен, используй `yarn`

2021-06-05 20:15 UTC, backmeupplz commented on package.json
> +    "@types/koa-router": "^7.4.2",
Новые зависимости не нужны.

2021-06-05 20:15 UTC, backmeupplz commented on src/app.ts
> +    router.post('/message', async ctx => {
Посмотри, как сделан `login`. Не вороти длинные велосипеды.

2021-06-05 20:15 UTC, backmeupplz commented on src/models/index.ts
> +    useFindAndModify: false,
Изменения в этом файле не нужны.

2021-06-05 20:15 UTC, backmeupplz commented on src/models/message.ts
> +const messageSchema = new Schema({
Используй typegoose, посмотри, как сделан `User`

2021-06-05 20:15 UTC, backmeupplz commented on src/server.ts
> +
В этом файле изменения не нужны

2021-06-05 20:15 UTC, backmeupplz commented on yarn.lock
> +"@types/koa-router@^7.4.2":
В этом файле изменения не нужны.

2021-06-05 20:16 UTC, gluknik commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
подумал, что нужно на свою БД заменить.
верну на место значит

2021-06-05 20:18 UTC, gluknik commented on package-lock.json
> +{
Удаляю

2021-06-05 20:20 UTC, gluknik commented on package.json
> +    "@types/koa-router": "^7.4.2",
убрал

2021-06-05 20:27 UTC, gluknik commented on src/models/index.ts
> +    useFindAndModify: false,
поправил

2021-06-05 20:35 UTC, gluknik commented on src/server.ts
> +
убираю

2021-06-05 20:37 UTC, gluknik commented on yarn.lock
> +"@types/koa-router@^7.4.2":
изменил

2021-06-07 05:09 UTC, gluknik commented on src/app.ts
> +    router.post('/message', async ctx => {
Сделал похожи образом. Правда не уверен что я правильно использовал функции из этого контроллера. Где я должен определять инстанс функции контроллера? Пока что я это делаю в самом app.ts

2021-06-08 19:36 UTC, backmeupplz requested changes

2021-06-08 19:36 UTC, backmeupplz commented on src/app.ts
>  import 'reflect-metadata'
В этом файле не должно быть изменений

2021-06-08 19:36 UTC, backmeupplz commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
Этот файл не надо удалять

2021-06-08 19:36 UTC, backmeupplz commented on src/controllers/message.ts
> +    const message = createMessage({
Почитай про promises и async/await, потом поправь код этого контроллера

2021-06-08 19:36 UTC, backmeupplz commented on src/models/index.ts
> +
Это ненужное изменение

2021-06-08 19:36 UTC, backmeupplz commented on src/models/message.ts
> +    .then((result) => {
Почитай про Promises и async/await и перепеши все на async/await.

2021-06-08 19:46 UTC, gluknik commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
извиняюсь
поправил

2021-06-08 19:53 UTC, gluknik commented on src/models/index.ts
> +
убрал

2021-06-08 19:53 UTC, gluknik commented on src/models/message.ts
> +const messageSchema = new Schema({
Тут у меня возникли сложности и я написал тебе в телегу

2021-06-08 20:04 UTC, gluknik commented on src/controllers/message.ts
> +    const message = createMessage({
кажется я забыл тут await написать, исправляю

2021-06-14 21:55 UTC, gluknik commented on src/models/message.ts
> +    .then((result) => {
переписал

2021-06-16 19:53 UTC, closed without merging