CRUD
Borodutch/backend-starter pull request #47
Opened 2021-06-18 08:44 UTC by fanamoner

**added CRUD**

2021-06-18 13:47 UTC, backmeupplz requested changes

2021-06-18 13:47 UTC, backmeupplz commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
Этот файл не нужно удалять

2021-06-18 13:47 UTC, backmeupplz commented on src/modules.d.ts
> +declare module "*";
Этот файл не нужен

2021-06-18 13:47 UTC, backmeupplz commented on src/models/message.ts
> +import { prop, getModelForClass } from "@typegoose/typegoose";
Добавь в prettier два правила:
```semi: false
qoutes: single```

2021-06-18 13:47 UTC, backmeupplz commented on src/models/message.ts
> +  author: string;
Сделай автора `Ref<User>` :)

2021-06-18 13:47 UTC, backmeupplz commented on src/middleware/auth.ts
> +export default async (ctx: Context, next: () => any) => {
Попробуй тип `next` найти получше

2021-06-18 13:47 UTC, backmeupplz commented on src/controllers/message.ts
> +    @CurrentUser() user: any
а он точно `any` или `User`?

2021-06-18 13:47 UTC, backmeupplz commented on src/controllers/message.ts
> +    @Body("body") body: string,
Лучше назвать это `text`, а не `body.body`

2021-06-18 13:47 UTC, backmeupplz commented on src/controllers/message.ts
> +      return ctx.throw(500, "Unable to create a message");
Это 403

2021-06-18 13:47 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Put("/:id")
Давай добавлять пустые строки между функциями

2021-06-18 13:47 UTC, backmeupplz commented on src/controllers/message.ts
> +  async listMessages(@CurrentUser() user: any, @Ctx() ctx: Context) {
При получении, редактировании и удалении сообщений, давай проверять авторство, чтобы человек не мог управлять чужими сообщениями

2021-06-19 01:46 UTC, fanamoner commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
Он есть)

2021-06-19 01:47 UTC, fanamoner commented on src/modules.d.ts
> +declare module "*";
Удалил

2021-06-19 01:47 UTC, fanamoner commented on src/models/message.ts
> +import { prop, getModelForClass } from "@typegoose/typegoose";
Добавил

2021-06-21 23:03 UTC, backmeupplz requested changes

2021-06-21 23:03 UTC, backmeupplz commented on .gitignore
> +.prettierrc.json
`gitignore` не стоит трогать

2021-06-27 13:46 UTC, closed without merging