crud msgs
Borodutch/backend-starter pull request #48
Opened 2021-06-18 20:05 UTC by earthspacon

2021-06-18 20:32 UTC, backmeupplz requested changes

2021-06-18 20:32 UTC, backmeupplz commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
Этот файл не нужно удалять

2021-06-18 20:32 UTC, backmeupplz commented on src/controllers/messages.ts
> +// import { Context } from 'koa'
Закомментированный код не нужно пушить

2021-06-18 20:32 UTC, backmeupplz commented on src/controllers/messages.ts
> +import { MsgsModel } from '@/models/msgModel'
У тебя уже в названии пути есть слово `models`, можешь назвать файл просто `message.ts`

2021-06-18 20:32 UTC, backmeupplz commented on src/controllers/messages.ts
> +    @Post('/create')
Поставь себе prettier с format on save и сделай отступы 2 пробелами

2021-06-18 20:32 UTC, backmeupplz commented on src/models/msgModel.ts
> +    { schemaOptions: { timestamps: true }, })
Вот тут prettier отлично отформатирует все

2021-06-21 14:38 UTC, backmeupplz requested changes

2021-06-21 14:38 UTC, backmeupplz commented on env.sample
В этом файле не нужны изменения

2021-06-21 14:38 UTC, backmeupplz commented on src/models/message.ts
> +export const MsgsModel = getModelForClass(Messages, {
не сокращай так, пожалуйста — пиши полностью `MessageModel`

2021-06-21 14:38 UTC, backmeupplz commented on src/models/message.ts
> +  messages?: string;
Тут только один message, не много

2021-06-21 14:38 UTC, backmeupplz commented on src/controllers/messages.ts
> +    await MsgsModel.findByIdAndUpdate(ctx.params.id, {
Почитай про декоратор @Params в amala

2021-06-21 23:01 UTC, backmeupplz requested changes

2021-06-21 23:01 UTC, backmeupplz commented on src/controllers/messages.ts
> +@Controller('/message')
Теперь создай middleware, которая будет верифицировать `token`, который нужно передавать в `headers` — она должна находить user и добавлять его в `ctx.state`. Дальше сделай так, чтобы пользователь добавлял сообщения только для себя, видел, редактировал и удалял только свои сообщения. Можешь создать поле `author` у `Message`

2021-06-21 23:01 UTC, backmeupplz commented on src/models/message.ts
> +class Messages {
Назови класс `Message`, тут не нужно множественное число

2021-06-21 23:01 UTC, backmeupplz commented on src/models/message.ts
> +  message?: string
Давай лучше это будет полем `text`.

2021-06-25 21:31 UTC, backmeupplz requested changes

2021-06-25 21:31 UTC, backmeupplz commented on src/models/message.ts
> +  author?: string
Это должен быть `Ref<User>`

2021-06-25 21:31 UTC, backmeupplz commented on src/models/message.ts
> +  text?: string
Определись: либо `required: true`, либо `?`

2021-06-25 21:31 UTC, backmeupplz commented on src/controllers/messages.ts
> +  @Flow(auth)
Если создаешь `middlewares`, то клади их в папку `middlewares` :)

2021-06-25 21:31 UTC, backmeupplz commented on src/controllers/messages.ts
> +  @Post('/')
Миддлваря аутентификации должна забирать хедер `token` из `request`, расшифровывать этот jwt, находить пользователя и добавлять его на `ctx.state`

2021-06-26 22:16 UTC, backmeupplz requested changes

2021-06-26 22:16 UTC, backmeupplz commented on src/controllers/messages.ts
> +  @Post('/auth')
Зачем тебе `@Post('/auth')`? Добавь `@Flow` ко всем нужным рутам.

2021-06-26 22:16 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +export const auth = async (ctx, next) => {
Пропиши типы параметрам

2021-06-26 22:16 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +    return 'Error'
Используй `ctx.throw`

2021-06-26 22:16 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +  const token = ctx.headers['Authorization'].split(' ')[1]
Работаем без `Bearer ` части, можешь не сплитить

2021-06-26 22:16 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +    ctx.state.user = await MessageModel.findOne({ user })
Что, если юзера нет?

2021-06-26 22:16 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +    await next()
Лучше не `await`, а `return` в этом случае

2021-06-26 22:16 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +    return 'Error'
Если у тебя есть `return`, то можно обойтись без `else`

2021-06-26 22:16 UTC, backmeupplz commented on src/models/message.ts
> +import { User } from './user'
Используй модульные имена для импортов

2021-06-26 22:16 UTC, backmeupplz commented on src/controllers/messages.ts
> +    await MessageModel.findByIdAndUpdate(id, { text: body })
Если ты используешь только `body.text`, так возьми только `body.text` из параметра :) декоратор `@Body` это позволяет

2021-06-26 22:24 UTC, earthspacon commented on src/controllers/messages.ts
> +  @Post('/auth')
Под `@Controller`ом можно один раз поставить?

2021-06-27 13:53 UTC, backmeupplz requested changes

2021-06-27 13:53 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +  const token = ctx.headers['Authorization']
Можно просто `ctx.headers.Authorization`

2021-06-27 13:53 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +    ctx.throw(400, 'token not found')
делай тут `return ctx.throw`, иначе выполнение может продолжиться

2021-06-27 13:53 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +    ctx.throw(400, 'user not found')
тут тоже `return ctx.throw`

2021-06-27 13:53 UTC, backmeupplz commented on src/controllers/messages.ts
> +    await newMsg.save()
Тестируй свои эндпоинты через insomnia.rest или postman. Это работать не будет, ведь `author — required`

2021-07-03 15:02 UTC, backmeupplz requested changes

2021-07-03 15:02 UTC, backmeupplz commented on src/controllers/login.ts
> +import * as jwt from 'jsonwebtoken'
Это не нужно сюда добавлять, у тебя есть `helpers/jwt`

2021-07-03 15:02 UTC, backmeupplz commented on src/controllers/messages.ts
> +    let thisuser = await MessageModel.findById(user._id)
Зачем тебе это, если у тебя уже есть `user` тут?

2021-07-03 15:02 UTC, backmeupplz commented on src/controllers/messages.ts
> +    thisuser.author = author
Автором всегда будет `@CurrentUser`, его не нужно передавать в `body`

2021-07-03 15:02 UTC, backmeupplz commented on src/controllers/messages.ts
> +    thisuser.text = text
Тут какая-то непонятность. У тебя есть пользователи и сообщения этих пользователей. Тут не пользователю нужно указывать текст, а создавать новое сообщение с таким текстом и пользователем в качесвте автора.

2021-07-03 15:02 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const thisuser = await MessageModel.findById(user._id)
Это же список сообщений, а не пользователь

2021-07-03 15:02 UTC, backmeupplz commented on src/controllers/messages.ts
> +    @Body('author') author,
Зачем тебе автор, если человеку нужно получить только свои сообщения?

2021-07-03 15:02 UTC, backmeupplz commented on src/controllers/messages.ts
> +  @Put('/:id')
`id` можно получить через `@Params`

2021-07-06 00:25 UTC, backmeupplz requested changes

2021-07-06 00:25 UTC, backmeupplz commented on src/controllers/login.ts
> +    ctx.append('Authorization', user.token)
Этого делать не нужно. Просто верни полученного `user`.

2021-07-06 00:25 UTC, backmeupplz commented on src/controllers/login.ts
> +    let user = await getOrCreateUser({
Включи линтер у себя в VSC, ты не меняешь user — он должен быть `const`

2021-07-06 00:25 UTC, backmeupplz commented on src/controllers/login.ts
> +  async email(@Body('email') email, @Ctx() ctx: Context) {
`ctx` тут не нужен

2021-07-06 00:25 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return { newMessage: message.text }
Просто верни статус 200

2021-07-06 00:25 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const texts = messages.map((item) => {
Зачем обрубать все сообщения? :) Просто верни массив сообщений

2021-07-06 00:25 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return { updatedMessage: message.text }
Тут можно просто вернуть `200`

2021-07-06 00:25 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const message = await MessageModel.findByIdAndUpdate(
Получается, все пользователи могут менять сообщения всех остальных пользователей? Давай это ограничим миддлварей.

2021-07-06 15:02 UTC, backmeupplz requested changes

2021-07-06 19:59 UTC, backmeupplz requested changes

2021-07-06 19:59 UTC, backmeupplz commented on src/controllers/middlewares/auth.ts
> +export const check = async (ctx: Context, next: Next) => {
Это другая middleware, которую нужно вынести в другой файл. Ну и назови ее более понятно.

2021-07-06 19:59 UTC, backmeupplz commented on src/controllers/messages.ts
> +    await MessageModel.findOneAndUpdate(
Зачем второй раз делать `find` тут и в других местах? Сообщение уже есть в `ctx.state`

2021-12-16 19:54 UTC, closed without merging