Model / controllers for CRUD operations
Borodutch/backend-starter pull request #49
Opened 2021-06-21 12:41 UTC by kaa777

2021-06-21 14:40 UTC, backmeupplz requested changes

2021-06-21 14:40 UTC, backmeupplz commented on src/controllers/messageController.ts
> +//TODO: User authentication as a middleware using @Flow decorator
Закомментированный код нужно убирать из PR

2021-06-21 14:40 UTC, backmeupplz commented on src/controllers/messageController.ts
> +import { createMessage, showAllMessages, findMessageById, deleteMessageById, updateMessage } from '@/models/messageModel';
Настрой prettier на `semi: false` и `quotes: single`

2021-06-21 14:40 UTC, backmeupplz commented on src/models/messageModel.ts
> +  })
Поставь себе prettier и включи `format on save`

2021-06-22 02:11 UTC, kaa777 reviewed
prettier installed and set up. both files are formatted, comments deleted

2021-06-22 13:35 UTC, backmeupplz requested changes

2021-06-22 13:35 UTC, backmeupplz commented on src/models/messageModel.ts
> +import { User } from './user'
Используй модульные импорты, как в других местах в проекте

2021-06-22 13:35 UTC, backmeupplz commented on src/models/messageModel.ts
> +  @prop({ required: true, index: true })
Почитай, что такое `index` и нужен ли он тут

2021-06-22 13:35 UTC, backmeupplz commented on src/models/messageModel.ts
> +  body: string
Давай лучше назовем это `text`

2021-06-22 13:35 UTC, backmeupplz commented on src/models/messageModel.ts
> +  const message = new MessageModel({ body: body }).save()
Думаю, есть смысл сделать `return` получившегося сообщения

2021-06-22 13:35 UTC, backmeupplz commented on src/models/messageModel.ts
> +  const message = new MessageModel({ body: body }).save()
Вместо `{ body: body }` можно писать просто `{ body }`

2021-06-22 13:35 UTC, backmeupplz commented on src/models/messageModel.ts
> +  const message = new MessageModel({ body: body }).save()
`save` возвращает Promise. Ему нужно делать `await`. Почитай, что такое Promises, с чем их едят, зачем они нужны. Потом почитай про async/await и как они отличаются от Promises.

2021-06-22 13:35 UTC, backmeupplz commented on src/models/messageModel.ts
> +  const message = new MessageModel({ body: body }).save()
В частности, у тебя тут одни async функции, но не использован await :) смысла делать функции async без использования await мало

2021-06-22 13:35 UTC, backmeupplz commented on src/controllers/messageController.ts
> +    return (ctx.body = showAllMessages())
Почитай про то, как работает `amala`. Тебе не нужно устанавливать `ctx.body`

2021-06-22 13:35 UTC, backmeupplz commented on src/controllers/messageController.ts
> +    return (ctx.body = showAllMessages())
Алсо, это работать не будет :) Тестируй свои Rest endpoints через Rest клиент типа Postman или insomnia.rest

2021-06-24 03:48 UTC, kaa777 commented on src/models/messageModel.ts
> +  @prop({ required: true, index: true })
убрал индексирование тела сообщений

2021-06-24 03:48 UTC, kaa777 commented on src/models/messageModel.ts
> +  body: string
refactored

2021-06-24 03:48 UTC, kaa777 commented on src/models/messageModel.ts
> +  const message = new MessageModel({ body: body }).save()
added

2021-06-24 03:48 UTC, kaa777 commented on src/models/messageModel.ts
> +  const message = new MessageModel({ body: body }).save()
refactored

2021-06-24 03:50 UTC, kaa777 commented on src/models/messageModel.ts
> +  const message = new MessageModel({ body: body }).save()
code rebuilt using proper async/await logic. also, added try/catch wrapping

2021-06-24 03:51 UTC, kaa777 commented on src/controllers/messageController.ts
> +    return (ctx.body = showAllMessages())
refactored. tested with the Postman from day1. after refactoring the code works as well.

2021-06-24 04:10 UTC, backmeupplz requested changes

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +import { getModelForClass, prop } from '@typegoose/typegoose'
Давай назовем этот файл просто `message.ts`

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +  try {
Вынеси try/catch на уровень контроллеров, не добавляй их на уровне прослойки к бд

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +    return message
Здесь можно обойтись без лишней переменной, просто `return new ...`

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +export async function showAllMessages() {
скорее `getMessages`?

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +    let messageList = await MessageModel.find()
Тут тоже можно обойтись без переменной

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +    let message = await MessageModel.findById(id)
И здесь можно обойтись без переменной

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +    await MessageModel.findByIdAndDelete({ _id: id })
Можно сделать просто `return MessageModel.findByIdAndDelete({ _id: id })`, получится то же самое. Почитай про Promises и async/await. А потом про то, что происходит при return промиса

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +    await MessageModel.findByIdAndUpdate({ _id: id }, { text })
Здесь тоже можно сделать просто return

2021-06-24 04:10 UTC, backmeupplz commented on src/models/messageModel.ts
> +export async function deleteMessageById(id: string) {
Когда избавишься от await, можно и функцию не делать async :)

2021-06-24 04:10 UTC, backmeupplz commented on src/controllers/messageController.ts
> +    const data: string = ctx.request.body
Почитай про `@Body` в amala

2021-06-24 04:10 UTC, backmeupplz commented on src/controllers/messageController.ts
> +    const messageId = ctx.params.id
Почитай про `@Params` в `amala`

2021-06-24 04:10 UTC, backmeupplz commented on src/controllers/messageController.ts
> +    const messageId = ctx.params.id
Если указываешь `@Params`, то используй его

2021-06-24 04:10 UTC, backmeupplz commented on src/controllers/messageController.ts
> +    deleteMessageById(messageId)
Наверное, здесь нужен await?

2021-06-26 18:37 UTC, kaa777 commented on src/models/messageModel.ts
> +export async function deleteMessageById(id: string) {
я возможно еще не очень хорошо понимаю применимость кейсов использования async/await. по моей логике, bd operations должны быть асинхронными. если надо иначе - я переделаю.

2021-06-26 21:02 UTC, kaa777 commented on src/controllers/messageController.ts
> +    const data: string = ctx.request.body
О, круто! Code refactored.

2021-06-26 21:02 UTC, kaa777 commented on src/models/messageModel.ts
> +    let messageList = await MessageModel.find()
Code refactored.

2021-06-26 21:02 UTC, kaa777 commented on src/models/messageModel.ts
> +export async function showAllMessages() {
Code refactored.

2021-06-26 21:03 UTC, kaa777 commented on src/models/messageModel.ts
> +    return message
Code refactored.

2021-06-26 21:03 UTC, kaa777 commented on src/models/messageModel.ts
> +  try {
Code refactored.

2021-06-26 21:03 UTC, kaa777 commented on src/models/messageModel.ts
> +import { getModelForClass, prop } from '@typegoose/typegoose'
file renamed

2021-06-26 21:21 UTC, kaa777 commented on src/controllers/messageController.ts
> +    const messageId = ctx.params.id
Code refactored. В силу особенностей koa-bodyparser работает только вместе с @Ctx

2021-06-26 21:23 UTC, kaa777 commented on src/controllers/messageController.ts
> +    const messageId = ctx.params.id
Code refactored

2021-06-26 21:30 UTC, kaa777 commented on src/controllers/messageController.ts
> +    deleteMessageById(messageId)
Code refactored

2021-06-26 22:09 UTC, backmeupplz requested changes

2021-06-26 22:09 UTC, backmeupplz commented on src/models/message.ts
> +  return await new MessageModel({ text }).save()
Почитай, как связаны `async/await` и Promises. И почитай, почему тут ты можешь не делать `return await` и можешь не указывать функцию `async`. Как и ниже тебе не нужны `return await`

2021-06-26 22:09 UTC, backmeupplz commented on src/controllers/messageController.ts
> +      console.log(error)
Вместо console.log(error) нужно, чтобы Koa сама ловила все exceptions. Она ловит по дефолту, можешь в контроллере даже не оборачивать код в `try/catch` :)

2021-06-26 22:09 UTC, backmeupplz commented on src/controllers/messageController.ts
> +  }
Добавь по пустой строке между методами класса

2021-06-26 22:09 UTC, backmeupplz commented on src/controllers/messageController.ts
> +class messageController {
Классы всегда пишутся с большой буквы

2021-06-26 22:09 UTC, backmeupplz commented on src/controllers/messageController.ts
> +import {
Не нужно в названии файла второй раз говорить "controller". Этот файл и так в папке `controllers`.

2021-06-28 02:27 UTC, kaa777 commented on src/models/message.ts
> +  return await new MessageModel({ text }).save()
code refactored

2021-06-28 03:21 UTC, kaa777 commented on src/controllers/messageController.ts
> +      console.log(error)
code refactored

2021-06-28 03:22 UTC, kaa777 commented on src/controllers/messageController.ts
> +  }
code refactored

2021-06-28 03:22 UTC, kaa777 commented on src/controllers/messageController.ts
> +class messageController {
code refactored

2021-06-28 03:23 UTC, kaa777 commented on src/controllers/messageController.ts
> +import {
filename changed to "message.ts"

2021-06-28 14:34 UTC, backmeupplz requested changes

2021-06-28 14:34 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await getMessages().catch(({ statusCode, message }) => {
Либо используй async/await, либо then/catch. Не мешай эти концепты друг с другом в одном месте.

2021-06-29 12:16 UTC, kaa777 commented on src/controllers/message.ts
> +    return await getMessages().catch(({ statusCode, message }) => {
then/catch removed from the controller

2021-06-29 12:18 UTC, kaa777 commented on src/models/messageModel.ts
> +export async function deleteMessageById(id: string) {
all model functions are now synchronous

2021-06-29 14:09 UTC, backmeupplz requested changes

2021-06-29 14:09 UTC, backmeupplz commented on src/controllers/message.ts
> +    // @Ctx() ctx: Context,
Не пушь закомментированный код в Pull Request. Если какой-то год нужен будет в будущем, коммить, удаляй и снова коммить. Гит будет помнить код в истории.

2021-06-29 14:09 UTC, backmeupplz commented on src/controllers/message.ts
> +import {
Теперь мне нужно, чтобы ты:
1. Добавил в `login` контроллер новый рут, который логинит человека только по email (без пароля, сейчас это нужно чисто для теста)
2. Добавил `middleware` типа `middlewares/auth.ts`, который будет брать поле `token` из `headers` запроса, проверять этот jwt и прикреплять пользователя к `ctx.state.user`.
3. Сделал так, чтобы сообщения создавались с полем `author` типа `Ref<User>`, а пользователи имели доступ только к своим сообщениями (почитай тут про `ctx.throw`)

2021-07-02 03:02 UTC, kaa777 commented on src/controllers/message.ts
> +    // @Ctx() ctx: Context,
сорян, торопился, дрогнула рука :) удалил

2021-07-17 19:59 UTC, kaa777 commented on src/controllers/message.ts
> +import {
Done

2021-07-27 00:24 UTC, backmeupplz requested changes

2021-07-27 00:24 UTC, backmeupplz commented on src/controllers/login.ts
> +      name: ctx.request.body.author.name,
Выглядит, как будто нужно использовать `@Body` декоратор :)

2021-07-27 00:24 UTC, backmeupplz commented on src/controllers/login.ts
> +    ctx.cookies.set('jwt', user.token)
Это бекенд, кукисы на бекенде использовать не нужно. Токен можно сохранить на фронтенде и подписывать им запросы

2021-07-27 00:24 UTC, backmeupplz commented on src/controllers/login.ts
> -    // verify the data
Это ненужное изменение

2021-07-27 00:24 UTC, backmeupplz commented on src/models/message.ts
> +import { User } from './user'
Используй модульные импорты

2021-07-27 00:24 UTC, backmeupplz commented on src/models/message.ts
> +export function createMessage(text: string, author: Ref<User>) {
Вряд ли у тебя там будет Ref, просто User здесь и далее запрашивай

2021-07-27 00:24 UTC, backmeupplz commented on src/models/message.ts
> +  return MessageModel.find(author)
Проверяй свой код тем же Postman или insomnia.rest. Это работать не будет.

2021-07-27 00:24 UTC, backmeupplz commented on src/middlewares/auth.ts
> +  const token = ctx.headers.authorization.split(' ')[1]
Давай без `Bearer`, просто кидай JWT сразу в `authorization`

2021-07-27 00:24 UTC, backmeupplz commented on src/middlewares/auth.ts
> +  ctx.state.user = await verify(token)
Это небезопасно :) любой JSON будешь считать пользователем? Найди пользователя в БД.

2021-07-27 00:24 UTC, backmeupplz commented on src/middlewares/auth.ts
> +  return await next()
Почитай, что такое `return await` и почему тут это не нужно. Почитай, что такое Promises и как они связаны с async/await

2021-07-27 00:24 UTC, backmeupplz commented on src/middlewares/auth.ts
> +export const userVerify = async function (messageId: string, user: Ref<User>) {
Выглядит, как что-то, что не должно быть в этом файле

2021-07-27 00:24 UTC, backmeupplz commented on src/controllers/message.ts
> +  async messageList(@CurrentUser() author: Ref<User>) {
Скорее всего, это будет просто `User`, а не `Ref`

2021-07-27 00:24 UTC, backmeupplz commented on src/controllers/message.ts
> +  async messageList(@CurrentUser() author: Ref<User>) {
Дальше тоже

2021-07-27 00:24 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Post('/add')
Может, просто `@Post('/')`?

2021-07-27 00:24 UTC, backmeupplz commented on src/controllers/message.ts
> +    if (await userVerify(messageId, user)) {
Это нужно сделать через `@Flow` миддлварю

2021-07-27 00:24 UTC, backmeupplz commented on src/controllers/message.ts
> +      ctx.throw(400, 'User is not is not allowed to view this message')
Выдаешь тут лишний раз информацию о том, что сообщение существует. Нужно просто возвращать 404.

2021-10-10 16:06 UTC, closed without merging