Fixed CRUD app
Borodutch/backend-starter pull request #58
Opened 2021-07-03 07:19 UTC by RobuASD

2021-07-03 15:11 UTC, backmeupplz requested changes

2021-07-03 15:11 UTC, backmeupplz commented on src/controllers/messages.ts
> +
Давай не добавлять лишние переносы строк

2021-07-03 15:11 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await getUserMessage()
`getUserMessages` тогда

2021-07-03 15:11 UTC, backmeupplz commented on src/controllers/messages.ts
> +  //get all messages
После `//` хороший тон — ставить пробел

2021-07-03 15:11 UTC, backmeupplz commented on src/controllers/messages.ts
> +// Validator classes
Определись, пишешь комментарии с большой или с маленькой буквы. При написании кода и комментариев нужна постоянность стиля.

2021-07-03 15:11 UTC, backmeupplz commented on src/controllers/messages.ts
> +  //get all messages
Да и зачем писать комментарий `get all messages`, когда название функции `getAllMessages`? :)

2021-07-03 15:11 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return (ctx.response.body = await createUserMessage(body.message))
В `amala` этого делать не нужно :) все, что вернешь из функции, попадет в `ctx.response.body`

2021-07-03 15:11 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const id = <string[]>ctx.request.query.id
Почитай про декоратор `@Params` в `amala`

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +//model for user message
Не добавляй ненужные комментарии, пожалуйста

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +import { User } from './user'
Используй модульные импорты

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ required: false })
Почему `false`? Сообщения без автора быть не может.

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +  if (id) {
Лучше разбей на две функции.

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +    return await UserMessageModel.find({}, (err, data) => {
Нам нужно вернуть только сообщения самого пользователя, а не все сообщения

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +export async function createUserMessage(message: string): Promise<UserMessage> {
Тебе не нужно указывать тип возврата, когда он `implicit`

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +export class UserMessage {
Можно это просто назвать `Message`

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +  const { _id: id } = await UserMessageModel.create({ message } as UserMessage)
Какой-то дико сложный способ создавать сообщения. Создай `new MessageModel`, а потом сделай на нем `save()`

2021-07-03 15:11 UTC, backmeupplz commented on src/models/message.ts
> +    (err, data) => {
Определись: ты коллбеки используешь или async/await?

2021-07-04 01:56 UTC, RobuASD commented on src/controllers/messages.ts
> +
Это prettier, не я

2021-07-04 01:57 UTC, RobuASD commented on src/controllers/messages.ts
> +  //get all messages
Сначала она так не называлась)

2021-07-04 02:03 UTC, RobuASD commented on src/models/message.ts
> +  @prop({ required: false })
Если бы у меня работал login, то да, но пока для тестов false

2021-07-04 02:06 UTC, RobuASD commented on src/models/message.ts
> +export async function createUserMessage(message: string): Promise<UserMessage> {
Забыл убрать..

2021-07-04 02:06 UTC, RobuASD commented on src/models/message.ts
> +    return await UserMessageModel.find({}, (err, data) => {
Работал бы логин, сделал бы все сообщения пользователя)

2021-07-04 02:08 UTC, RobuASD commented on src/models/message.ts
> +  if (id) {
Хорошо, жаль что нельзя перегружать, может и можно но я не знаю как

2021-07-04 02:46 UTC, RobuASD commented on src/models/message.ts
> +  const { _id: id } = await UserMessageModel.create({ message } as UserMessage)
Такой способ был где-то в оф. документации к typegoose или mongoose)

2021-07-07 19:37 UTC, backmeupplz requested changes

2021-07-07 19:37 UTC, backmeupplz commented on src/controllers/login.ts
> +class emailInput {
Названия классов должны быть с заглавной буквы

2021-07-07 19:37 UTC, backmeupplz commented on src/controllers/login.ts
> +// Validator classes
Можно не писать этот комментарий, и так понятно

2021-07-07 19:37 UTC, backmeupplz commented on src/controllers/messages.ts
> +// Validator classes
Можно не писать этот комментарий, и так понятно

2021-07-07 19:37 UTC, backmeupplz commented on src/middlewares/authUser.ts
> +  const token = <string>ctx.headers.token
Лучше кастить тип через `as`

2021-07-07 19:37 UTC, backmeupplz commented on src/controllers/login.ts
> +  async addUserMessage(@Body({ required: true }) body: emailInput) {
Назови эту функцию понятнее

2021-07-07 19:37 UTC, backmeupplz commented on src/models/message.ts
> +  return await messageModel.find({ user: user })
Почитай, что такое `return await`, посмотри, что такое `async/await`, `Promises` и как они связаны. А потом измени эту функцию.

2021-07-07 19:37 UTC, backmeupplz commented on src/models/message.ts
> +export const messageModel = getModelForClass(Message)
Добавь таймстампы сюда

2021-07-07 19:37 UTC, backmeupplz commented on src/models/message.ts
> +  return await messageModel.find({ user: user })
Да и ниже в функциях тоже

2021-07-07 19:37 UTC, backmeupplz commented on src/models/message.ts
> +  return await messageModel.find({ _id: id, user: user })
`user: user` можно заменить на `user` :) с `_id` тоже можно провернуть такой трюк

2021-07-07 19:37 UTC, backmeupplz commented on src/models/message.ts
> +  return await messageModel.find({ _id: id, user: user })
Эта функция, кстати, не используется, вроде как.

2021-07-07 19:37 UTC, backmeupplz commented on src/models/message.ts
> +export async function deleteMessages(id: string[], user: User) {
Давай остановимся на удалении одного сообщения

2021-07-07 19:37 UTC, backmeupplz commented on src/controllers/messages.ts
> +export default class MessageController {
Теперь тебе нужно еще ограничить доступы пользователей к чужим сообщениям. Чтобы нельзя было их удалять, редактировать, видеть.

2021-07-08 11:04 UTC, RobuASD commented on src/models/message.ts
> +export async function deleteMessages(id: string[], user: User) {
Но это работает...

2021-07-08 12:28 UTC, RobuASD commented on src/controllers/messages.ts
> +export default class MessageController {
Теперь при попытке доступа появляется ошибка

2021-07-08 16:30 UTC, backmeupplz requested changes

2021-07-08 16:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    if (messages.length > 0) return messages
То есть, если у меня нет сообщений, то вернется 404? Я хотел бы, чтобы вернулся `[]`, это же не ошибка

2021-07-08 16:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    else ctx.throw(404, 'messages not found')
После `if/return` не нужно делать `else`

2021-07-08 16:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    if (messages.length > 0) return messages
Не стоит `if` без `{}` писать

2021-07-08 16:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const message = await getMessage(id, user)
`getMessage` должен возвращать `Message`, а не `Message[]`, по очевидным причинам :)

2021-07-09 13:59 UTC, RobuASD commented on src/middlewares/checkUser.ts
> +  if (String(message?.user._id) === String(ctx.state.user.id)) {
Работает  только так, не понимаю почему у них разные типы.
Через as string не работает..

2021-07-09 21:29 UTC, backmeupplz requested changes

2021-07-09 21:29 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await changeMessage(ctx.state.message?._id, body.message)
У тебя уже есть тут `ctx.state.message`, давай не будем делать лишний find :)

2021-07-25 16:57 UTC, closed without merging