CRUD Messages
Borodutch/backend-starter pull request #61
Opened 2021-07-25 12:51 UTC by JordanMikel

Man I love family

2021-07-25 17:00 UTC, backmeupplz requested changes

2021-07-25 17:00 UTC, backmeupplz commented on src/models/message.ts
> +  return MessageModel.find(user)
Проверяешь через Postman или Insomnia? Это не будет работать :)

2021-08-02 15:07 UTC, backmeupplz requested changes

2021-08-02 15:07 UTC, backmeupplz commented on src/controllers/message.ts
> +import { Controller, Ctx, Delete, Get, Post, Put,} from 'amala'
Поставь себе prettier и включи `format on save` :) неформатированный код невозможно читать

2021-08-02 15:07 UTC, backmeupplz commented on src/controllers/message.ts
> +    return readMessages(ctx.state.user, ctx.state.text)
Почитай про декораторы `@Body` и `@CurrentUser` в `amala`, тебе нужно, как минимум, использовать их

2021-08-02 15:07 UTC, backmeupplz commented on src/controllers/message.ts
> +    return readMessages(ctx.state.user, ctx.state.text)
Тестируй свои эндпоинты через Postman, а монго смотри через Robo 3T. Сделай так, чтобы эндпоинты *работали*, а не просто были как-то написаны :)

2021-08-02 15:07 UTC, backmeupplz commented on src/controllers/message.ts
> +    return readMessages(ctx.state.user, ctx.state.text)
Например, `ctx.state.user` и `ctx.state.text` будут `undefined`, ты же туда ничего не записал. Тебе, наверное, нужно смотреть на `ctx.request` :) читай документацию `amala`

2021-08-02 15:07 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ index: true, required: true })
Это работать не будет без `ref:` — читай документацию `typegoose`

2021-08-10 22:50 UTC, backmeupplz requested changes

2021-08-10 22:50 UTC, backmeupplz commented on src/middlewares/CheckUser.ts
> +    if(message.user == user.id) {
поставь себе prettier и включи format on save, неформатированный код невозможно читать

2021-08-10 22:50 UTC, backmeupplz commented on src/controllers/login.ts
> +  @Post('/email')
Я бы добавил между методами пустую строку

2021-08-10 22:50 UTC, backmeupplz commented on src/controllers/message.ts
> +
Ты либо добавляй пустую строку между методами, либо нет

2021-08-10 22:50 UTC, backmeupplz commented on src/middlewares/CheckUser.ts
> +export async function CheckUser(ctx: Context, next: Next){
функции не пишутся с большой буквы

2021-08-10 22:50 UTC, backmeupplz commented on src/middlewares/CheckUser.ts
> +    const message = await MessageModel.findById(ctx.params.id)
Что, если оно не найдено?

2021-08-10 22:50 UTC, backmeupplz commented on src/middlewares/CheckUser.ts
> +    }
Что будет, если это сообщение не пользователя?

2021-08-10 22:50 UTC, backmeupplz commented on src/middlewares/CheckUser.ts
> +    const message = await MessageModel.findById(ctx.params.id)
Может, сохраним `message` в `ctx.state`, чтобы потом переиспользовать?

2021-09-01 19:50 UTC, backmeupplz requested changes

2021-09-01 19:50 UTC, backmeupplz commented on src/middlewares/auth.ts
> +  if (token) {
Если токена нет — нужно кинуть ошибку

2021-09-01 19:50 UTC, backmeupplz commented on src/middlewares/auth.ts
> +      ctx.state.user = await getOrCreateUser(verifyToken)
Не нужно создавать на этом этапе пользователя.

2021-09-01 19:50 UTC, backmeupplz commented on src/middlewares/CheckUser.ts
> +  const msgId = ctx.params.id
Не сокращай там, где не нужно сокращать. Это `messageId`

2021-09-01 19:50 UTC, backmeupplz commented on src/middlewares/CheckUser.ts
> +  if (message.user['_id'] == user.id) {
А если нет? Может, нужно вернуть ошибку?

2021-09-01 19:50 UTC, backmeupplz commented on src/middlewares/CheckUser.ts
> +import { MessageModel } from '@/models/message'
У тебя функция с маленькой буквы начинается, а название файла с большой

2021-09-01 19:50 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await MessageModel.deleteOne({ _id: ctx.state.message.id })
Зачем нам возвращать из этого метода удаленное сообщение?

2021-09-13 16:42 UTC, backmeupplz requested changes

2021-09-13 16:42 UTC, backmeupplz commented on src/middlewares/auth.ts
> +   if (!token) {
Поставь себе prettier и включи format on save. Неформатированный код невозможно читать

2021-09-13 16:42 UTC, backmeupplz commented on src/middlewares/auth.ts
> +    ctx.response.status = 404
Статус можно не указывать, если `ctx.throw` используешь

2021-09-13 16:42 UTC, backmeupplz commented on src/middlewares/auth.ts
> +   if (!token) {
Если до этого проверил `!!token`, не нужно снова проверять `!token` — это бинарное условие же :)

2021-09-13 16:42 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +  if (message.user['_id'] == user.id) {
Не используй `[]`

2021-09-30 17:29 UTC, backmeupplz requested changes

2021-09-30 17:29 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +  if (message.user._id == user.id) {
А что, если `message` нет?

2021-10-01 08:30 UTC, JordanMikel commented on src/middlewares/checkUser.ts
> +  if (message.user._id == user.id) {
тогда он не зареганный?

2021-10-01 16:40 UTC, backmeupplz requested changes

2021-10-01 16:40 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +  if (message.user._id == user.id) {
Если он зареганный и кидает левый message id?

2021-10-01 16:40 UTC, backmeupplz commented on src/models/message.ts
> +  user: Ref<User>
Давй назовем это `author`

2021-10-01 16:40 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +    return ctx.throw("User don't have any messages or unauthorized")
Сообщения могут быть, но id просто не существует

2021-10-01 16:40 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +    return ctx.throw('you cannot change others messages')
Нужно возвращать 404, сам факт знания о том, что у кого-то существует определенное сообщение — это приватная информация

2021-10-01 16:40 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +    return ctx.throw('you cannot change others messages')
Точнее, возвращать то же, что возвращается, если сообщения нет

2021-10-01 16:40 UTC, backmeupplz commented on src/middlewares/auth.ts
> +  ctx.state.user = await UserModel.findOne({ token })
Что, если пользователь по этому токену не найден?

2021-10-01 16:40 UTC, backmeupplz commented on src/controllers/message.ts
> +    return ctx.state.message.save()
Тестировал этот эндпоинт через Postman? :)

2021-10-01 17:24 UTC, JordanMikel commented on src/controllers/message.ts
> +    return ctx.state.message.save()
Да, вроде работает

2021-10-04 17:21 UTC, backmeupplz requested changes

2021-10-04 17:21 UTC, backmeupplz commented on src/controllers/message.ts
> +    return ctx.state.message.save()
Что возвращает?

2021-12-16 19:54 UTC, closed without merging