Add CRUD for messages
Borodutch/backend-starter pull request #64
Opened 2021-08-07 18:13 UTC by Semion120

Please, check my project

2021-08-07 20:44 UTC, backmeupplz requested changes

2021-08-07 20:44 UTC, backmeupplz commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
В этом файле не должно быть изменений

2021-08-07 20:44 UTC, backmeupplz commented on package.json
>      "koa": "^2.13.1",
В этом файле не должно быть изменений

2021-08-07 20:44 UTC, backmeupplz commented on src/app.ts
> +
Это ненужное изменение

2021-08-07 20:44 UTC, backmeupplz commented on src/controllers/crud.ts
> +import { Context } from 'koa'
Поставь prettier и включи format on save, неформатированный код невозможно читать

2021-08-07 20:44 UTC, backmeupplz commented on src/controllers/crud.ts
> +import { Context } from 'koa'
Этот файл выглядит, как `controllers/message.ts`

2021-08-07 20:44 UTC, backmeupplz commented on src/controllers/crud.ts
> +@Controller('/crud')
CRUD – это общее название, тут у тебя контроллер сообщений

2021-08-07 20:44 UTC, backmeupplz commented on src/controllers/crud.ts
> +        @Post('/add')
Можно просто `@Post('/)`

2021-08-07 20:44 UTC, backmeupplz commented on src/controllers/crud.ts
> +        async addAnsw( @Body('msg') message: string | number ) {
Это может быть только `string`. Не сокращай там, где не надо, например, тут не `msg`, а `message`

2021-08-07 20:44 UTC, backmeupplz commented on src/controllers/login.ts
> +import { Body, Controller, Ctx, Get, Post } from 'amala'
Это ненужное изменение

2021-08-07 20:44 UTC, backmeupplz commented on src/models/index.ts
> +export const msgModel = mongoose.model('Message', new mongoose.Schema({ msg: String }));
Создавать модель сообщения нужно так же, как создана модель юзера, через `typegoose`

2021-08-07 20:44 UTC, backmeupplz commented on yarn.lock
>      "@types/koa-compose" "*"
В этом файле не должно быть изменений

2021-08-07 22:23 UTC, Semion120 commented on .env.sample
> -MONGO=mongodb://localhost:27017/todorant
Сделал

2021-08-07 22:24 UTC, Semion120 commented on package.json
>      "koa": "^2.13.1",
удалил через yarn. Удалось лишние две библиотеки

2021-08-07 22:24 UTC, Semion120 commented on src/app.ts
> +
Убрал

2021-08-07 22:25 UTC, Semion120 commented on src/controllers/crud.ts
> +import { Context } from 'koa'
prettier был поставлен, format on save включил

2021-08-07 22:25 UTC, Semion120 commented on src/controllers/crud.ts
> +@Controller('/crud')
Изменил

2021-08-07 22:25 UTC, Semion120 commented on src/controllers/crud.ts
> +        @Post('/add')
Сделал

2021-08-07 22:25 UTC, Semion120 commented on src/controllers/crud.ts
> +        async addAnsw( @Body('msg') message: string | number ) {
Сделал

2021-08-07 22:25 UTC, Semion120 commented on src/controllers/login.ts
> +import { Body, Controller, Ctx, Get, Post } from 'amala'
Убрал, сделал чтобы проверить какую то из гипотез

2021-08-07 22:26 UTC, Semion120 commented on src/models/index.ts
> +export const msgModel = mongoose.model('Message', new mongoose.Schema({ msg: String }));
Сделал в отдельном файле /models/message.ts

2021-08-07 22:26 UTC, Semion120 commented on yarn.lock
>      "@types/koa-compose" "*"
Лишнее должно было удалиться когда я удалял две лишние библиотеки через yarn

2021-08-24 00:44 UTC, backmeupplz requested changes

2021-08-24 00:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +import { Controller, Get, Post, Put, Delete, Flow, Body, Params } from 'amala';
Поставь prettier и включи format on save. Код без форматирования невозможно читать.

2021-08-24 00:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +@Controller('/messagesCtrl')
`/message` достаточно будет

2021-08-24 00:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +    export class MsgController {
Не сокращай там, где не надо. Это `MessageController`

2021-08-24 00:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +        async addAnsw( @Body('message') message: string ) {
Исправь везде сокращения, непонятно, что эта функция делает

2021-08-24 00:44 UTC, backmeupplz commented on src/controllers/messages.ts
> +          return `Сообщение сохранено. ID:${newMessage._id}. Текст: ${newMessage}`
Возвращать стоит само сообщение. Тестируй код, который пишешь, через Postman или Insomnia

2021-08-24 00:44 UTC, backmeupplz commented on src/models/index.ts
> +import * as mongoose from 'mongoose';
В этом файле не должно быть изменений

2021-08-24 00:44 UTC, backmeupplz commented on src/models/message.ts
> +    msg: string
Хватит сокращать. Если поле `message` звучит глупо в модели `Message`, значит это и вправду неправильно. Название для этого поля — `text`

2021-08-25 12:54 UTC, Semion120 commented on src/models/message.ts
> +    msg: string
Сделано

2021-08-25 12:54 UTC, Semion120 commented on src/models/index.ts
> +import * as mongoose from 'mongoose';
Сделал форматирование, точка с запятой ушли

2021-08-25 12:54 UTC, Semion120 commented on src/controllers/messages.ts
> +          return `Сообщение сохранено. ID:${newMessage._id}. Текст: ${newMessage}`
Сделал возврат самого сообщения. Тестирую через постман

2021-08-25 12:55 UTC, Semion120 commented on src/controllers/messages.ts
> +        async addAnsw( @Body('message') message: string ) {
Прошелся по файлам в которые писал код, в них исправил все сокращения

2021-08-25 12:56 UTC, Semion120 commented on src/controllers/messages.ts
> +    export class MsgController {
Сделал

2021-08-25 12:57 UTC, Semion120 commented on src/controllers/messages.ts
> +@Controller('/messagesCtrl')
сделал

2021-08-25 12:57 UTC, Semion120 commented on src/controllers/messages.ts
> +import { Controller, Get, Post, Put, Delete, Flow, Body, Params } from 'amala';
Разобрался с проблемой, теперь форматирование в рабочих файлах должна быть сделана

2021-08-29 20:30 UTC, backmeupplz requested changes

2021-08-29 20:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +import { Controller, Get, Post, Put, Delete, Body, Params } from 'amala'
У тебя контроллер `message`, а файл назван `messages` :)

2021-08-29 20:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +  async addMessage(@Body('message') text: string) {
А может, и аргумент назовем `text`? :)

2021-08-29 20:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +  async putMessage(@Params('id') _id: string, @Body('text') newText: string) {
Может, не `newText`, а `text`?

2021-08-29 20:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const message = await messageModel.findOne({ _id })
А можно еще `updateOne` использовать

2021-08-29 20:30 UTC, backmeupplz commented on src/models/message.ts
> +export class Message {
Теперь тебе нужно:
1. Добавить сообщению автора
2. Добавить в `login` контроллер функцию логина через email (без пароля)
3. Добавлять токен аутентификации пользователя в запросы
4. Создать middleware, который будет по предоставленному токену находить пользователя и добавлять его в `ctx.state`
5. Сделать так, чтобы юзер мог редактировать, добавлять, удалять, смотреть только свои сообщения

2021-08-30 17:51 UTC, Semion120 commented on src/controllers/messages.ts
> +import { Controller, Get, Post, Put, Delete, Body, Params } from 'amala'
Сделал

2021-08-30 17:57 UTC, Semion120 commented on src/controllers/messages.ts
> +  async addMessage(@Body('message') text: string) {
сделал, просто мне показалось отпралять аргумет мессадж логичнее

2021-08-30 18:00 UTC, Semion120 commented on src/controllers/messages.ts
> +  async putMessage(@Params('id') _id: string, @Body('text') newText: string) {
Сделал, мне просто не понравилось как выглядит: message.text = text. С newText вроде симпотнее :) 

Я исправил как ты сказал

2021-09-04 15:41 UTC, Semion120 commented on src/controllers/messages.ts
> +    const message = await messageModel.findOne({ _id })
Сделал

2021-09-04 15:41 UTC, Semion120 commented on src/models/message.ts
> +export class Message {
Сделал

2021-09-05 22:22 UTC, backmeupplz requested changes

2021-09-05 22:22 UTC, backmeupplz commented on src/controllers/login.ts
> +// For testing
Не пушь закомментированный код в PR

2021-09-05 22:22 UTC, backmeupplz commented on src/models/message.ts
> +  author: string
Автор должен быть типом User. Почитай про Ref в typegoose

2021-09-05 22:22 UTC, backmeupplz commented on src/middleware/authMiddleware.ts
> +  ctx.state.user = await verify(token)
Тут нужно найти и вытянуть объект юзера из БД, а не из токена.

2021-09-06 15:25 UTC, Semion120 commented on src/controllers/login.ts
> +// For testing
убрал

2021-09-06 15:29 UTC, Semion120 commented on src/models/message.ts
> +  author: string
Сделал

2021-09-06 15:32 UTC, Semion120 commented on src/middleware/authMiddleware.ts
> +  ctx.state.user = await verify(token)
Сделал

2021-09-06 15:58 UTC, backmeupplz requested changes

2021-09-06 15:58 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ required: false, ref: () => User })
Либо делай `required: true`, либо `author?: Ref<User>`

2021-09-06 15:58 UTC, backmeupplz commented on src/middleware/authMiddleware.ts
> +  return await next()
Почитай, почему тут не нужен `return await`

2021-09-06 15:58 UTC, backmeupplz commented on src/middleware/authMiddleware.ts
> +  ctx.state.user = await UserModel.findOne({ token })
А что если пользователь с таким `token` не найден?

2021-09-06 15:58 UTC, backmeupplz commented on src/models/message.ts
> +export const messageModel = getModelForClass(Message)
Давай-ка с большой буквы `MessageModel` напишем

2021-09-06 15:58 UTC, backmeupplz commented on src/controllers/message.ts
> +    if (deletedText['deletedCount'] === 0) {
Зачем тут `[]`? Тайпскрипт ругается? Не зря ругается! Посмотри на тип `deletedText`

2021-09-06 15:58 UTC, backmeupplz commented on src/controllers/message.ts
> +        reason: 'Its not your messge or mistake in ID',
Давать юзеру сам факт наличия этого сообщения нельзя, если он не авторизован его читать или редактировать

2021-09-06 15:58 UTC, backmeupplz commented on src/controllers/message.ts
> +        reason: 'Its not your messge or mistake in ID',
Т.е. надо 404 возвращать

2021-09-06 15:58 UTC, backmeupplz commented on src/controllers/message.ts
> +      return { type: 'Error', reason: 'Cant find this message in your profile' }
Что-то тут прямо повторение кода из `Delete`. Может, сделать миддлварю, которая проверяет авторство сообщения по его `id`? А может, еще и в `ctx.state` запихивать найденное сообщение, чтобы потом его просто удалить\редактировать без лишнего поиска? :)

2021-09-06 15:58 UTC, backmeupplz commented on src/middleware/authMiddleware.ts
> +import { Context, Next } from 'koa'
`src/middleware/authMiddleware.ts` — найди лишнее в пути файла, ну, повторяющееся :)

2021-09-06 16:11 UTC, Semion120 commented on src/models/message.ts
> +  @prop({ required: false, ref: () => User })
Сделал

2021-09-06 20:17 UTC, Semion120 commented on src/models/message.ts
> +  @prop({ required: false, ref: () => User })
Сделал 2 вариант

2021-09-06 20:31 UTC, Semion120 commented on src/middleware/authMiddleware.ts
> +  return await next()
Если я правильно понимаю: возвращать нет смысла, ибо это декоратор и его задача сделать действия перед выполнением основного кода. По сути нужно использовать: await next(), чтобы просто передать выполнение дальше.

2021-09-06 20:59 UTC, Semion120 commented on src/middleware/authMiddleware.ts
> +  ctx.state.user = await UserModel.findOne({ token })
Добавил обработку если токен не найден. Теперь выдает 401 ошибку

2021-09-06 21:01 UTC, Semion120 commented on src/models/message.ts
> +export const messageModel = getModelForClass(Message)
Сделал

2021-09-06 21:09 UTC, Semion120 commented on src/controllers/message.ts
> +    if (deletedText['deletedCount'] === 0) {
У меня на [ ] не ругается, что бы я не делал. Я посмотрел тип - object. Выглядит он так: { n: 0, ok: 1, deletedCount: 0 }. Я изменений не сделал, ибо не понимаю, что исправить.

2021-09-06 21:18 UTC, Semion120 commented on src/controllers/message.ts
> +        reason: 'Its not your messge or mistake in ID',
теперь возвращает 404

2021-09-07 13:16 UTC, Semion120 commented on src/controllers/message.ts
> +      return { type: 'Error', reason: 'Cant find this message in your profile' }
Сделал вроде, посмотри как тебе. Вроде кода уменьшил в контроллере и обращений к базе меньше стало. Но это не точно

2021-09-07 13:17 UTC, Semion120 commented on src/middleware/authMiddleware.ts
> +import { Context, Next } from 'koa'
понял, теперь просто src/middleware/auth.ts

2021-09-07 15:45 UTC, backmeupplz requested changes

2021-09-07 15:45 UTC, backmeupplz commented on src/models/message.ts
> +  author?: Ref<User>
Сообщений без автора быть не может, сделай `required`

2021-09-07 15:45 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Flow(authMessage)
Тут тоже нужен auth. Ты можешь несколько миддлварь собирать в цепочку.

2021-09-07 15:45 UTC, backmeupplz commented on src/middleware/auth.ts
> +export const authMessage = async (ctx: Context, next: Next) => {
1. Это отдельная миддлваря и должна быть в отдельном файле
2. Эта миддлваря должна находить message по id и проверять, имеет ли к этому сообщению доступ `ctx.state.user`, которого ты до этой миддлвари аутентифицировал

2021-09-07 19:38 UTC, Semion120 commented on src/models/message.ts
> +  author?: Ref<User>
Сделал

2021-09-07 19:43 UTC, Semion120 commented on src/controllers/message.ts
> +  @Flow(authMessage)
сделал

2021-09-07 20:13 UTC, Semion120 commented on src/middleware/auth.ts
> +export const authMessage = async (ctx: Context, next: Next) => {
Вроде разделил, теперь работает как ты говоришь

2021-09-07 20:24 UTC, backmeupplz requested changes

2021-09-07 20:24 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ required: true, ref: () => User })
Почитай про `index` еще

2021-09-07 20:24 UTC, backmeupplz commented on src/middleware/checkRights.ts
> +  const token = ctx.state.user.token
Тебе не нужен тут токен

2021-09-07 20:24 UTC, backmeupplz commented on src/middleware/checkRights.ts
> +  }).populate('author')
Тебе не нужно тут делать `populate`

2021-09-07 20:24 UTC, backmeupplz commented on src/middleware/checkRights.ts
> +    _id: ctx.request.url.split('/')[2],
У тебя есть `ctx.params`

2021-09-07 20:24 UTC, backmeupplz commented on src/middleware/checkRights.ts
> +  if (token != message.author.token) {
Почему не проверить id юзера?

2021-09-07 20:24 UTC, backmeupplz commented on src/middleware/checkRights.ts
> +    return (ctx.response.status = 404)
Никогда не возвращай результат в `()`. Установи статус и сделай `ctx.throw`

2021-09-07 20:24 UTC, backmeupplz commented on src/middleware/checkRights.ts
> +  if (token != message.author.token) {
`!=` нельзя использовать, только `!==`

2021-09-07 20:24 UTC, backmeupplz commented on src/middleware/auth.ts
> +    ctx.throw(401, 'Token is undefined')
Функция все равно идет дальше, нужно делать `return`

2021-09-07 20:24 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Flow(auth)
А еще можно сделать `Flow` на весь контроллер

2021-09-07 20:34 UTC, Semion120 commented on src/middleware/checkRights.ts
> +  const token = ctx.state.user.token
убрал

2021-09-07 20:34 UTC, Semion120 commented on src/middleware/checkRights.ts
> +  }).populate('author')
убрал

2021-09-07 20:46 UTC, Semion120 commented on src/middleware/checkRights.ts
> +    _id: ctx.request.url.split('/')[2],
Использовал

2021-09-07 20:48 UTC, Semion120 commented on src/middleware/checkRights.ts
> +  if (token != message.author.token) {
сделал

2021-09-07 21:02 UTC, Semion120 commented on src/middleware/checkRights.ts
> +    return (ctx.response.status = 404)
Сделал

2021-09-07 21:03 UTC, Semion120 commented on src/middleware/checkRights.ts
> +  if (token != message.author.token) {
Только возникла проблема в сравнении этом. Там сравниваются два объекта, но отображаются при получении как ID. Мне пришлось применить toString(). Ты это увидишь

2021-09-07 21:04 UTC, Semion120 commented on src/middleware/auth.ts
> +    ctx.throw(401, 'Token is undefined')
сделал

2021-09-07 21:05 UTC, Semion120 commented on src/controllers/message.ts
> +  @Flow(auth)
сделал

2021-09-07 21:09 UTC, backmeupplz requested changes

2021-09-07 21:09 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Get('/')
Добавь пустую строку между методами :)

2021-09-07 21:09 UTC, backmeupplz commented on src/middleware/auth.ts
> +    return ctx.throw
Почитай, что такое `ctx.throw` и как он используется. Это неверное использование этой функции.

2021-09-07 21:09 UTC, backmeupplz commented on src/middleware/auth.ts
> +  await next()
Почему просто не сделать `return next()`? Почитай про Promises, async/await и как они связаны с return.

2021-09-07 21:09 UTC, backmeupplz commented on src/middleware/auth.ts
> +  if (ctx.state.user === null) {
А можно просто сделать `!ctx.state.user`?

2021-09-07 21:09 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ required: true, ref: () => User })
И добавь его тут :)

2021-09-08 13:06 UTC, Semion120 commented on src/controllers/message.ts
> +  @Get('/')
сделал

2021-09-08 14:33 UTC, Semion120 commented on src/middleware/auth.ts
> +  await next()
использовал return next(). Работает. Асинхронные функции при вызове всегда возвращают обещание, которое потом заменяется значением возвращаемым. await - дожидается выполнения функции справа. return - возвращает значение.  

 Функция next передает контроль дальше, следующей мидлвари. Когда мидлвари закончатся, как я понял, выполнение пойдет обратно с next() по мидлварям в обратном направлении. С помощью return мы явно покажем, что мидлвари закончились

Поэтому можно не использовать await, но явно показать конец мидлвари с помощью return.

2021-09-08 14:33 UTC, Semion120 commented on src/middleware/auth.ts
> +  if (ctx.state.user === null) {
Сделал, можно

2021-09-08 16:01 UTC, Semion120 commented on src/middleware/auth.ts
> +    return ctx.throw
сделал

2021-09-08 16:04 UTC, Semion120 commented on src/models/message.ts
> +  @prop({ required: true, ref: () => User })
Добавил индекс

2021-09-08 16:23 UTC, backmeupplz requested changes

2021-09-08 16:23 UTC, backmeupplz commented on src/controllers/message.ts
> +    return ctx.state.message.remove()
Может, тут тоже await нужен?

2021-09-08 19:57 UTC, Semion120 commented on src/controllers/message.ts
> +    return ctx.state.message.remove()
сделал

2021-09-12 19:05 UTC, closed without merging