Fix #65 pull request problems
Borodutch/backend-starter pull request #66
Opened 2021-08-11 14:23 UTC by letxbeazero

2021-08-11 18:21 UTC, backmeupplz requested changes

2021-08-11 18:21 UTC, backmeupplz commented on src/models/user.ts
> +  telegramId?: number
Лучше давай без этого изменения

2021-08-11 18:21 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ index: true })
Чего-то у тебя много опциональных полей. Они все должны быть required

2021-08-11 18:21 UTC, backmeupplz commented on src/controllers/message.ts
> +      .then((deleteMessage) => {
Либо используй await, либо then/catch, не мешай

2021-08-11 18:21 UTC, backmeupplz commented on src/controllers/login.ts
>    @Post('/facebook')
Не трогай то, что не сломано. Тебе здесь нужно только добавить один метод `/email`

2021-08-11 18:21 UTC, backmeupplz commented on src/controllers/login.ts
> +  async loginTestUser(@Body() leadData: { name: string; email: string }) {
А можно еще сделать `@Body('name')`, почитай про этот декоратор побольше

2021-08-11 18:21 UTC, backmeupplz commented on src/controllers/message.ts
> +    const messageProps: any = ctx.request.body
*Никогда* не используй any. Здесь нужн использовать `@Body`. А когда хочешь использовать `any`, всегда используй `unknown`.

2021-08-11 18:21 UTC, backmeupplz commented on src/controllers/message.ts
> +  async getMessage(@Params() params: any) {
А можно еще сделать `@Params('id')`. Почитай про этот декоратор

2021-08-11 18:21 UTC, backmeupplz commented on src/controllers/message.ts
> +    const id = ctx.originalUrl.split('/')[2]
Ну это же `@Params` :)

2021-08-12 11:52 UTC, letxbeazero commented on src/controllers/login.ts
> +  async loginTestUser(@Body() leadData: { name: string; email: string }) {
Но в таком случае, я получу доступ к переменной name, но мне нужен еще и email. Или я неверно тебя понял?

2021-08-12 11:53 UTC, letxbeazero commented on src/controllers/login.ts
>    @Post('/facebook')
Я использую @Body в некоторых местах. Мне не использовать его?

2021-08-12 12:01 UTC, letxbeazero commented on src/models/user.ts
> +  telegramId?: number
В `helpers/verifyTelegramPayload.ts` в `TelegramLoginPayload` у `id` значенеи `number`. Но в `LoginOptions` для `telegramId` ты используешь значение `string`. Т.е. мы пытаемся типу `string` присвоить данные с типом `number`. Поэтому я вижу ошибку: 
```
Type 'number' is not assignable to type 'string'.ts(2322)
user.ts(43, 3): The expected type comes from property 'telegramId' which is declared here on type 'LoginOptions'
(property) LoginOptions.telegramId?: string
```
Поэтому я поменял значение на `string`

2021-08-12 16:44 UTC, backmeupplz requested changes

2021-08-12 16:44 UTC, backmeupplz commented on src/models/user.ts
> +  telegramId?: number
Ок, логично.

2021-08-12 17:49 UTC, closed without merging