Fixed problem from #68 pull request
Borodutch/backend-starter pull request #70
Opened 2021-08-13 00:00 UTC by letxbeazero

2021-08-14 22:55 UTC, backmeupplz requested changes

2021-08-14 22:55 UTC, backmeupplz commented on src/controllers/login.ts
> -
Это ненужное изменение

2021-08-14 22:55 UTC, backmeupplz commented on src/models/message.ts
> +import mongoose = require('mongoose')
А зачем здесь mongoose?

2021-08-14 22:55 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ ref: () => User })
Почему не сделать это required?

2021-08-14 22:55 UTC, backmeupplz commented on src/helpers/authMiddleware.ts
> +    if (err) {
Либо используй async/await, либо коллбеки — не одновременно

2021-08-14 22:55 UTC, backmeupplz commented on src/helpers/authMiddleware.ts
> +  next()
Если юзер не найден, надо, наверное, кидать `unauthorized`

2021-08-14 22:55 UTC, backmeupplz commented on src/controllers/message.ts
> +    await Message.findByIdAndDelete(id, function (err, deleteMessage) {
Тут и везде — не мешай коллбеки и async/await

2021-08-14 22:55 UTC, backmeupplz commented on src/controllers/message.ts
> +    const user = currentUser._id
Можно и без этого обойтись

2021-08-14 22:55 UTC, backmeupplz commented on src/controllers/message.ts
> +    const user = currentUser._id
Просто передавай полного `user` в объект создания мессаги

2021-08-14 22:55 UTC, backmeupplz commented on src/controllers/message.ts
> +    const message = await Message.findById(id)
Если автор не тот, нужно вернуть 404. Если сообщения по id нет, нужно вернуть 404

2021-08-14 22:55 UTC, backmeupplz commented on src/controllers/message.ts
> +    console.log(ctx.request.body)
Лишние console.log не надо пушить

2021-08-14 22:55 UTC, backmeupplz commented on src/controllers/message.ts
> +    const messageProps: any = ctx.request.body
Есть `@Body` + отвыкай использовать `any`

2021-08-15 16:58 UTC, backmeupplz requested changes

2021-08-15 16:58 UTC, backmeupplz commented on src/helpers/authMiddleware.ts
> +  const result = (await verify(token)) as { email: string }
Можно сделать просто:
```typescript
const { email } = (await verify(token)) as { email: string }
```

2021-08-15 16:58 UTC, backmeupplz commented on src/helpers/authMiddleware.ts
> +  const foundedUser = await User.findOne({ email })
Это можно просто назвать `user`

2021-08-15 16:58 UTC, backmeupplz commented on src/helpers/authMiddleware.ts
> +  if (foundedUser && Object.keys(foundedUser).length) {
`Object.keys(foundedUser).length` — эта проверка точно не нужна :) `findOne` вернет `undefined`, если документ не найден

2021-08-15 16:58 UTC, backmeupplz commented on src/helpers/authMiddleware.ts
> +  next()
Как насчет сначала проверить на отсутствие `user`, а потом продолжить, как обычно? Вместо `if/else` будет только один `if`

2021-08-15 16:58 UTC, backmeupplz commented on src/controllers/message.ts
> +    return message
а можно и просто сделать `return await` :)

2021-08-15 16:58 UTC, backmeupplz commented on src/controllers/message.ts
> +    } else {
Не надо делать `return/else`. Можно и без `else` обойтись :)

2021-08-15 16:58 UTC, backmeupplz commented on src/controllers/message.ts
> +        if (err) {
Либо используй `async/await`, либо коллбеки — не мешай

2021-08-15 16:58 UTC, backmeupplz commented on src/controllers/message.ts
> +      if (err) {
Либо используй `async/await`, либо коллбеки — не мешай

2021-08-15 16:58 UTC, backmeupplz commented on src/controllers/message.ts
> +    if (String(message.user) === String(user._id)) {
Ну и как насчет в других местах тоже это проверить? :) А если будешь копипастить код, задумайся, нарушаешь ли ты DRY. Может, миддлварю можно написать?

2021-08-15 19:41 UTC, letxbeazero commented on src/controllers/message.ts
> +        if (err) {
Я здесь использую только коллбеки. Или я неправильно тебя понял?

2021-08-15 19:41 UTC, letxbeazero commented on src/controllers/message.ts
> +      if (err) {
Я здесь использую только коллбеки.

2021-08-15 19:59 UTC, backmeupplz requested changes

2021-08-15 19:59 UTC, backmeupplz commented on src/helpers/checkUsersMiddleware.ts
> +  const message = await Message.findById(id)
Можно его добавить в `ctx.state` и использовать дальше :)

2021-08-15 19:59 UTC, backmeupplz commented on src/controllers/message.ts
> +@Flow([authMiddleware])
Если у тебя только одна миддлваря, можно не оборачивать ее в массив

2021-08-15 19:59 UTC, backmeupplz commented on src/controllers/message.ts
> +import { off } from 'process'
А это тут зачем?

2021-08-15 19:59 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await Message.findById(id)
Хм, прикольно было бы, если бы сообщение было в `ctx.state`! Тогда дважды его искать не нужно будет

2021-08-17 21:44 UTC, backmeupplz requested changes

2021-08-17 21:44 UTC, backmeupplz commented on package.json
> +    "test": "yarn jest --forceExit --setupFiles dotenv/config"
Это не нужно

2021-08-17 21:44 UTC, backmeupplz commented on src/__tests__/message.ts
> +describe('Message endpoint', () => {
Проверь ошибки тоже

2021-08-18 09:31 UTC, letxbeazero commented on package.json
> +    "test": "yarn jest --forceExit --setupFiles dotenv/config"
Если это убрать, то я получаю ошибку: 
`Error: secretOrPrivateKey must have a value
`
Тест не видит данные с .env, и не может получить данные JWT переменной с секретным ключом.

2021-08-18 16:43 UTC, closed without merging