Сделал CRUD, скорее всего неверно
Borodutch/backend-starter pull request #73
Opened 2021-09-26 08:03 UTC by Bleb1k

2021-09-26 17:03 UTC, backmeupplz requested changes

2021-09-26 17:03 UTC, backmeupplz commented on yarn.lock
В этом файле не должно быть изменений.

2021-09-26 17:03 UTC, backmeupplz commented on src/app.ts
> +app.use(async (ctx, next) => {
В этом файле не должно быть изменений

2021-09-26 17:03 UTC, backmeupplz commented on src/models/message.ts
> +  text: String
Можно использовать не `String`, а `string`

2021-09-26 17:03 UTC, backmeupplz commented on src/controllers/messages.ts
> +  @Get('/:id')
Добавляй дополнительные пустые строки между методами класса, пожалуйста

2021-09-26 17:03 UTC, backmeupplz commented on src/controllers/messages.ts
> +    message.save()
Может, `await`?

2021-09-26 17:03 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return 'Updated succesfully!'
Не возвращай plain text. В конце концов, верни `{ success: true }` или вообще измененное сообщение

2021-09-27 01:06 UTC, Bleb1k commented on src/server.ts
> +})
Prettier стоит, Format on save включен

2021-09-29 20:03 UTC, closed without merging