CRUD Refactored 2.0
Borodutch/backend-starter pull request #76
Opened 2021-10-10 05:53 UTC by Bleb1k

2021-10-10 16:04 UTC, backmeupplz requested changes

2021-10-10 16:04 UTC, backmeupplz commented on src/controllers/login.ts
> +  @Post('/test')
Давай назовем его `email`? :)

2021-10-10 16:04 UTC, backmeupplz commented on src/models/message.ts
> +import { User } from './user'
Используй красивые импорты, а не относительные

2021-10-10 16:04 UTC, backmeupplz commented on src/controllers/messages.ts
> +  async receiveMessages() {
Можно это назвать `getMessages`

2021-10-10 16:04 UTC, backmeupplz commented on src/controllers/messages.ts
> +import { MessageModel } from '@/models/message'
Теперь тебе нужно:
1. Сделать middleware, который будет проверять `token` авторизации из `headers` реквеста, проверять, есть ли этот пользователь, добавлять его в `ctx.state.user`
2. При создании сообщения, сохранять автора сообщения
3. Давать пользователям редактировать, удалять и смотреть только свои сообщения
4. Если у пользователя нет доступа к сообщению, пользователь не должен знать о его существовании, надо возвращать 404

2021-10-14 15:45 UTC, backmeupplz commented on yarn.lock
>      "@types/keygrip" "*"
В этом файле не должно быть изменений

2021-10-14 15:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +    return ctx.throw('Unauthorized')
Давай использовать `@hapi/boom` для exceptions

2021-10-14 15:48 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +  if (!message.author._id) {
Скорее всего, тебе нужно сделать тут https://typegoose.github.io/typegoose/docs/api/functions/typeguards/is-ref-type

2021-10-14 15:48 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +  const user = ctx.state.User
Это не будет работать. У тебя поле `user` с большой буквы

2021-10-14 15:49 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +  const user = ctx.state.User
Тестируй свой код через postman или insomnia

2021-10-14 15:49 UTC, backmeupplz commented on src/middleware/auth.ts
> +    ctx.status = 401
Мы делаем `ctx.throw`

2021-10-19 13:39 UTC, backmeupplz requested changes

2021-10-19 13:39 UTC, backmeupplz commented on src/models/message.ts
> +  author: Ref<User['_id']>
Тут нужно указать просто `Ref<User>`

2021-10-19 13:39 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +    console.log('frog')
Не пушь лишние console.log'и в пулл реквесты

2021-10-19 13:39 UTC, backmeupplz commented on src/middleware/auth.ts
> +    ctx.state.user = await UserModel.findOne({ token })
Что, если пользователь не найден?

2021-10-19 13:39 UTC, backmeupplz commented on src/middleware/auth.ts
> +    console.log(err)
Не нужно лишний раз логировать эту ошибку

2021-10-19 13:39 UTC, backmeupplz commented on src/controllers/messages.ts
> +    @Body('newMessage') text: string,
Давай добавим валидаций во все эндпоинты новые

2021-10-19 13:39 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.create({ text, author })
Можно не делать `return await`

2021-10-20 11:59 UTC, Bleb1k commented on src/middleware/auth.ts
> +    ctx.state.user = await UserModel.findOne({ token })
отправляет Unauthorized

2021-10-20 15:45 UTC, backmeupplz commented on src/controllers/login.ts
> +  async email(@Body('name') name: string, @Body('email') email: string) {
Давай добавим валидацию

2021-10-20 15:46 UTC, backmeupplz commented on src/controllers/messages.ts
> +    await MessageModel.create({ text, author })
Давай вернем созданное сообщение, можно `await` заменить на `return`

2021-10-20 15:46 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.findById(id)
В `amala` больше не нужен `return await`, можно просто писать `return`

2021-10-20 15:46 UTC, backmeupplz commented on src/controllers/messages.ts
> +    @Body('newMessage') text: string,
Добавь валидацию во все новые эндпоинты

2021-10-20 15:46 UTC, backmeupplz commented on src/controllers/messages.ts
> +    @Body('newMessage') text: string,
Алсо, зачем называть `newMessage` аргумент, когда это `text`?

2021-10-20 15:49 UTC, backmeupplz commented on src/controllers/messages.ts
> +@Controller('/message')
Либо файл назови `message.ts`, либо путь сделай `messages` :)

2021-10-20 15:50 UTC, backmeupplz commented on src/middleware/auth.ts
> +    ctx.state.user = await UserModel.findOne({ token })
Давай я тебя еще раз спрошу: что, если пользователь не найден?

2021-10-20 15:51 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +    return ctx.throw(notFound())
`else/return` делать не надо

2021-11-15 17:43 UTC, backmeupplz requested changes

2021-11-15 17:43 UTC, backmeupplz commented on src/controllers/message.ts
> +/* eslint-disable require-await */
Не отключай линтер. Это правило включено намерено.

2021-11-15 17:43 UTC, backmeupplz commented on src/controllers/message.ts
> +  // @Flow(checkUser)  если это тут поставить, будет ошибка 404
Потому что тебе нужно поправить это.

2021-11-15 17:43 UTC, backmeupplz commented on src/controllers/message.ts
> +  async createMessage(@Body('text') text: string, @CurrentUser() author: User) {
Нужны везде валидации

2021-11-28 18:01 UTC, backmeupplz requested changes

2021-11-28 18:01 UTC, backmeupplz commented on src/controllers/message.ts
> +    return text
Почему все сообщение не вернуть?

2021-11-28 18:01 UTC, backmeupplz commented on src/controllers/message.ts
> +    @State('message') { _id }: MessageValidator
А можно прямо в `ctx.state.message` изменить `text` и сделать `save()`

2021-11-28 18:01 UTC, backmeupplz commented on src/controllers/message.ts
> +  deleteMessage(@State('message') { _id }: MessageValidator) {
Выглядит совсем не как `MessageValidator`, а как что-то другое, что проверяет наличие `id`

2021-11-28 23:41 UTC, Bleb1k commented on src/controllers/login.ts
> +    return user
Выдаёт ошибку 
Property 'strippedAndFilled' does not exist on type 'FindOrCreateResult<User>'

2021-11-28 23:44 UTC, Bleb1k commented on src/models/message.ts
> +  author!: Ref<User, Types.ObjectId>
если я не прописываю вручную, то оно дополнительно в конец добавляет "| undefined", а мне такого не надо, если это можно исправить другим способом, буду рад исправить

2021-11-28 23:49 UTC, Bleb1k commented on src/middleware/checkUser.ts
> +    return next()
оно сломает "POST: localhost:1337/message/"
мне нужно при отсутствии сообщения проверить если запрос является POST, и если да, просто продолжать алгоритм, не ища несуществующих сообщений с пустым id

2021-11-28 23:49 UTC, Bleb1k commented on src/middleware/checkUser.ts
> +  if (message.author.toString() != user._id.toString()) {
Спасибо!

2021-11-28 23:50 UTC, Bleb1k commented on src/controllers/message.ts
> +  @Flow(checkUser)
точно
Спасибо

2021-11-28 23:50 UTC, Bleb1k commented on src/middleware/checkUser.ts
> +    return next()
Пролистал ниже, понял ошибку, спасибо!

2021-11-28 23:51 UTC, Bleb1k commented on src/validators/Message.ts
> +  message?: Message
Хорошо

2021-11-28 23:53 UTC, Bleb1k commented on src/controllers/message.ts
> +  deleteMessage(@State('message') { _id }: MessageValidator) {
Упс... :)

2021-11-29 00:20 UTC, backmeupplz commented on src/models/message.ts
> +  author!: Ref<User, Types.ObjectId>
Не нужно прописывать

2021-11-29 00:58 UTC, backmeupplz requested changes

2021-11-29 00:58 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +  if (message.author.toString() != user.id) {
Давай проверим, что `author` тут не `isDocumen`, а ref?

2021-11-29 00:58 UTC, backmeupplz commented on src/controllers/message.ts
> +  getMessages(@State({ required: true }) { text }: MessageValidator) {
Стейту не нужен валидатор. И давай полностью сообщение возвращать, а не только текст

2021-11-29 01:42 UTC, backmeupplz requested changes

2021-11-29 01:42 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +  if (isRefType(message.author, Types.ObjectId)) {
Тут же можно обойтись без `Types.ObjectId`, нет?

2021-11-29 01:42 UTC, backmeupplz commented on src/controllers/message.ts
> +  deleteMessage(@State({ required: true }) { text }: MessageValidator) {
Тебе не нужно валидировать `State`

2021-11-29 08:11 UTC, Bleb1k commented on src/middleware/checkUser.ts
> +  if (isRefType(message.author, Types.ObjectId)) {
Нет, там 2 обязательных ввода

2021-12-01 17:30 UTC, backmeupplz requested changes

2021-12-01 17:30 UTC, backmeupplz commented on src/controllers/login.ts
> +    const user = await findOrCreateUser({ name, email })
Вместо этого, сделай `const { doc: user } = ...`, юзай destruction :)

2021-12-01 17:30 UTC, backmeupplz commented on src/controllers/message.ts
> +    ctx.state.message.text = text
Давай использовать `@State`

2021-12-06 17:06 UTC, backmeupplz requested changes

2021-12-06 17:06 UTC, backmeupplz commented on src/controllers/message.ts
> +    @State({ required: true }) { text }: MessageValidator,
Тебе не нужно валидировать `State`. `@State('message') message: Message`

2021-12-14 14:45 UTC, backmeupplz requested changes

2021-12-14 14:45 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +  if (isRefType(message.author, Types.ObjectId)) {
Что, если это не так? Мы просто не проверяем авторство тогда?

2021-12-14 14:45 UTC, backmeupplz commented on src/controllers/message.ts
> +export default class messageController {
Классы надо называть с большой буквы

2021-12-14 14:45 UTC, backmeupplz commented on src/controllers/message.ts
> +  getMessages(@State('message') message: DocumentType<Message>) {
`getMessages` или `getMessage`? Если это `getMessage`, то можем добавить `getMessages` с пагинацией через `skip` и `limit`?

2022-01-10 11:18 UTC, Bleb1k commented on src/controllers/message.ts
> +  getMessages(@State('message') message: DocumentType<Message>) {
Это getMessage

2022-01-23 14:35 UTC, backmeupplz requested changes

2022-01-23 14:35 UTC, backmeupplz commented on src/__tests__/login.ts
> +jest.setTimeout(18000000)
Это изменение не нужно

2022-01-23 15:18 UTC, closed without merging