CRUD "messages"
Borodutch/backend-starter pull request #82
Opened 2021-11-16 14:52 UTC by sodapng

2021-11-17 18:14 UTC, backmeupplz requested changes

2021-11-17 18:14 UTC, backmeupplz commented on src/app.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Не отключай линтер

2021-11-17 18:14 UTC, backmeupplz commented on src/app.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Не отключай линтер

2021-11-17 18:14 UTC, backmeupplz commented on src/app.ts
> +    // const router = new Router()
Не пушь закомментированный код

2021-11-17 18:14 UTC, backmeupplz commented on src/app.ts
> +import router from './routes/todoRoutes'
Используй модульные, а не относительные импорты

2021-11-17 18:14 UTC, backmeupplz commented on src/app.ts
> +    router.redirect('/', '/todos')
В этом файле не должно быть изменений

2021-11-17 18:14 UTC, backmeupplz commented on src/controllers/todoController.ts
> +  await TodoModel.find()
Не используй `then/catch`, у тебя есть `async/await`

2021-11-17 18:14 UTC, backmeupplz commented on src/models/todo.ts
> +import { Schema, model } from 'mongoose'
Используй `typegoose`, посмотри, как другая модель сделана

2021-11-17 18:14 UTC, backmeupplz commented on src/routes/todoRoutes.ts
> +router.get('/todos', todoContctoller.todosGet)
Мы используем `amala`, посмотри, как сделан другой контроллер — `login`

2021-11-18 21:11 UTC, backmeupplz requested changes

2021-11-18 21:11 UTC, backmeupplz commented on src/models/todo.ts
> +  public title: string
`Public` — это дефолтное значение, можно не указывать его

2021-11-18 21:11 UTC, backmeupplz commented on src/controllers/todoController.ts
> +    await new TodoModel(body).save()
Как насчет вернуть созданный объект?

2021-11-18 21:11 UTC, backmeupplz commented on src/controllers/todoController.ts
> +  async deleteTodo(@Params('id') id) {
Добавь валидацию

2021-11-18 21:11 UTC, backmeupplz commented on src/controllers/todoController.ts
> +  async updateTodo(@Params('id') id, @Body({ required: true }) body) {
Добавь валидацию

2021-11-18 21:11 UTC, backmeupplz commented on src/controllers/todoController.ts
> +    await TodoModel.findByIdAndUpdate(id, body)
Давай вернем измененный объект

2021-11-19 18:07 UTC, backmeupplz requested changes

2021-11-19 18:07 UTC, backmeupplz commented on src/validators/Todo.ts
> +  @IsOptional()
Кажется, не должно быть опциональным

2021-11-19 18:07 UTC, backmeupplz commented on src/validators/Todo.ts
> +  @IsOptional()
И это не должно быть опциональным

2021-11-19 18:07 UTC, backmeupplz commented on src/controllers/todoController.ts
> +    return await new TodoModel(body).save()
Тут не нужен `return await`, как и в других местах

2021-11-19 18:07 UTC, backmeupplz commented on src/controllers/todoController.ts
> +  @Post('/add')
Можно даже сделать `@Post('/')`

2021-11-19 18:07 UTC, backmeupplz commented on src/controllers/todoController.ts
> +  @Put('/update/:id')
Можно даже сделать `@Put('/:id')`

2021-11-19 18:07 UTC, backmeupplz commented on src/controllers/todoController.ts
> +  @Delete('/delete/:id')
Можно даже сделать `@Delete('/:id')`

2021-11-20 14:47 UTC, backmeupplz requested changes

2021-11-20 14:47 UTC, backmeupplz commented on src/controllers/todoController.ts
> +const middlewareRedirect = async (ctx, next) => {
Тебе не нужны редиректы

2021-11-20 14:47 UTC, backmeupplz commented on src/controllers/todoController.ts
> +let path: string
Это хак, он тебе не нужен

2021-11-20 14:47 UTC, backmeupplz commented on src/controllers/todoController.ts
> +    path = `/${todo._id}`
Тебе это не нужно. Просто сделай `return new TodoModel(body).save()`

2021-11-20 14:47 UTC, backmeupplz commented on src/controllers/todoController.ts
> +    path = '/'
И это тебе не нужно. Все, что ты сделаешь `return` в `amala`, пойдет в `response.body`

2021-11-20 14:47 UTC, backmeupplz commented on src/validators/Todo.ts
> +  title: string
Давай уберем `title` из сообщения и оставим только `text`

2021-11-20 15:35 UTC, sodapng commented on src/controllers/message.ts
> +    return MessageModel.findByIdAndDelete(params.id)
Необходимо ли возвращать удаленное сообщение?

2021-11-20 15:39 UTC, backmeupplz requested changes

2021-11-20 15:39 UTC, backmeupplz commented on src/controllers/message.ts
> +    return MessageModel.findByIdAndDelete(params.id)
Нет, можно просто сделать await

2021-11-20 15:39 UTC, backmeupplz commented on src/controllers/message.ts
> +import { Body, Controller, Delete, Get, Params, Post, Put } from 'amala'
Теперь тебе нужно:
1. Создать новый путь в `login`, который будет логинить только по имейлу (чисто для твоих тестов)
2. Создать middleware, который будет проверять токен в `request.headers.token` на валидность и прикреплять полученного `user` в `ctx.state.user`.
3. Добавить в Message еще и поле author с рефом на модель User
4. У каждого сообщения должен быть автор, человек должен видеть и знать о существовании только своих сообщений

2021-11-22 15:05 UTC, backmeupplz requested changes

2021-11-22 15:05 UTC, backmeupplz commented on src/validators/message.ts
> +  iat: number
Думаю, это не нужно

2021-11-22 15:05 UTC, backmeupplz commented on src/validators/message.ts
> +import { IsEmail, IsMongoId } from 'class-validator'
Тут разные валидаторы, скорее всего, нужно разбить по файлам, это не только `message`

2021-11-22 15:05 UTC, backmeupplz commented on src/models/message.ts
> +  author: Ref<User, string>
Сделай просто `Ref<User>`

2021-11-22 15:05 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ required: true, ref: () => User, type: () => String })
Не нужно указывать `type`, зато нужен будет `index`

2021-11-22 15:05 UTC, backmeupplz commented on src/middleware/auth.ts
> +    ctx.state.user = await verify(token)
Давай попробуем прямо `User` сюда закинуть, а не какой-то объект?

2021-11-25 18:33 UTC, backmeupplz requested changes

2021-11-25 18:33 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ required: true, index: true })
Нужно добавить сюда `ref:`

2021-11-25 18:33 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +      ctx.status = 404
Есть `ctx.throw` и `@hapi/boom`, используй их

2021-11-25 18:33 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +  const id: number = ctx.params.id
Точно `number`? Может, это все еще `string`?

2021-11-25 18:33 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +      const { author } = (await MessageModel.findById(id)) as Message
`author` тут будет `ObjectId`. Тебе нужно сделать `populate`, а потом проверить через `isDocument`

2021-11-25 18:33 UTC, backmeupplz commented on src/middleware/auth.ts
> +  iat: number
Тебе не нужен `iat`

2021-11-25 18:33 UTC, backmeupplz commented on src/middleware/auth.ts
> +      const user = await UserModel.findById(id)
Что, если `user` тут `undefined`?

2021-11-25 18:33 UTC, backmeupplz commented on src/controllers/message.ts
> +    return new MessageModel({ author: name, text }).save()
Кидай целого `user` в `author`, не стесняйся

2021-11-25 18:33 UTC, backmeupplz commented on src/controllers/message.ts
> +    return {
Хватит `200` статуса

2021-11-26 17:46 UTC, backmeupplz requested changes

2021-11-26 17:46 UTC, backmeupplz commented on src/models/message.ts
> +export class Message {
Давай между импортами и экспортом поставим пустую строку

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +    ctx.throw(notFound('invalid parameter name'))
Давай тут сделаем `return`?

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +      .exec()) as Message
`exec` не нужен

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +      .populate('author', '_id')
`'_id'` тут не нужен

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +    if (isDocument(author)) {
Давай, вместо этого, сделаем `if (!isDocument(author)) { throw new Error(...) }`?

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +      if (author._id.toString() === ctx.state.user._id.toString()) {
Там есть `id` — это и есть стринговый `_id`

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +    const { author } = (await MessageModel.findById(id)
Может, кинуть `notFound`, если сообщение не найдено?

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +        ctx.throw(forbidden('access denied'))
Сначала проверяй на ошибку, потом возвращай успешный результат, тогда сможешь меньше нестить скобочки

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +      ctx.throw(notFound('message not found'))
Лучше у всех `ctx.throw` делать `return`, это 100% позволит убедиться, что функция дальше не пойдет

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +      ctx.throw(err)
Тебе нужно в любом случае кидать эту ошибку. Можешь отсюда `try/catch` вообще убрать

2021-11-26 17:46 UTC, backmeupplz commented on src/middleware/auth.ts
> +  try {
Тебе не нужен тут `try/catch`

2021-11-26 17:46 UTC, backmeupplz commented on src/controllers/message.ts
> +    @Params() params: MongoIdMessage,
Можешь прямо тут сделать `{ id }`

2021-11-26 20:06 UTC, sodapng commented on src/middleware/auth.ts
> +  try {
Тогда я не смогу обработать ошибку:

- `JsonWebTokenError: invalid token
- at Object.module.exports [as verify] (C:\Users\Kamran\Documents\GitHub\backend-starter\node_modules\jsonwebtoken\verify.js:75:17)
- at C:\Users\Kamran\Documents\GitHub\backend-starter\dist\helpers\jwt.js:26:13
- at new Promise (<anonymous>)
- at verify (C:\Users\Kamran\Documents\GitHub\backend-starter\dist\helpers\jwt.js:25:12)
- at C:\Users\Kamran\Documents\GitHub\backend-starter\dist\middleware\auth.js:25:44
- at Generator.next (<anonymous>)
- at C:\Users\Kamran\Documents\GitHub\backend-starter\dist\middleware\auth.js:8:71
- at new Promise (<anonymous>)
- at __awaiter (C:\Users\Kamran\Documents\GitHub\backend-starter\dist\middleware\auth.js:4:12)
- at auth (C:\Users\Kamran\Documents\GitHub\backend-starter\dist\middleware\auth.js:17:29)
- `

2021-11-26 21:54 UTC, backmeupplz requested changes

2021-11-26 21:54 UTC, backmeupplz commented on src/middleware/checkUser.ts
> +    return ctx.throw(notFound('message not found'))
Это message not found, а не author not found :)

2021-11-29 15:13 UTC, sodapng commented
**`success`**

2021-11-29 15:13 UTC, closed without merging