CRUD
Borodutch/backend-starter pull request #85
Opened 2021-11-18 17:45 UTC by aprobelb

- сделал CRUD
- добавил аутентификацию

2021-11-18 20:49 UTC, backmeupplz requested changes

2021-11-18 20:49 UTC, backmeupplz commented on .vscode/settings.json
> +  "prettier.vueIndentScriptAndStyle": true
Этот файл трогать не нужно

2021-11-18 20:49 UTC, backmeupplz commented on src/validators/MongoMessage.ts
> +export default class MongoMessage {
Добавь пустую строку между импортом и экспортом

2021-11-18 20:49 UTC, backmeupplz commented on src/middleware/auth.ts
> +  const user = await UserModel.findOne({ filter: ctx.headers.token })
Нужно токен еще и проверить, валидный ли он. Для этого есть функция в `helpers`

2021-11-18 20:49 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.find({ author })
Здесь не нужен `return await`

2021-11-18 20:49 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await new MessageModel({ author, text }).save()
Здесь не нужен `return await`

2021-11-18 20:49 UTC, backmeupplz commented on src/controllers/messages.ts
> +  async addMessage(@CurrentUser() author: User, @Body('text') text: string) {
Добавь сюда валидацию

2021-11-18 20:49 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.updateOne({ _id: id }, { text: text })
Здесь не нужен `return await`

2021-11-18 20:49 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.deleteOne({ _id: id })
Здесь не нужен `return await`

2021-11-18 20:49 UTC, backmeupplz commented on src/controllers/messages.ts
> +  async deleteMessage(@Ctx() ctx: Context, @Params('id') id: string) {
Добавь валидацию

2021-11-18 20:49 UTC, backmeupplz commented on src/controllers/messages.ts
> +  async editMessage(
Добавь валидацию

2021-11-19 15:25 UTC, aprobelb commented on src/controllers/messages.ts
> +    return await MessageModel.find({ author })
а что тогда нужно?

> Здесь не нужен `return await`

2022-01-16 14:31 UTC, closed without merging