Add CRUD messages
Borodutch/backend-starter pull request #88
Opened 2021-11-30 17:45 UTC by chmsv

- Add CRUD messages

2021-12-01 17:33 UTC, backmeupplz requested changes

2021-12-01 17:33 UTC, backmeupplz commented on src/models/message.ts
> +  username!: Ref<User>
Тут скорее весь `user`, а не просто `username`

2021-12-01 17:33 UTC, backmeupplz commented on src/models/message.ts
> +    index: true,
давай не будем создавать индексы по вероятно длинным текстовым строкам :)

2021-12-01 17:33 UTC, backmeupplz commented on src/models/message.ts
> +export const MessageModel = getModelForClass(Message, {
Используй `@modelOptions`

2021-12-01 17:33 UTC, backmeupplz commented on src/controllers/messages.ts
> +    @Body('message') message: string,
Добавь валидацию во все новые пути

2021-12-02 23:01 UTC, backmeupplz requested changes

2021-12-02 23:01 UTC, backmeupplz commented on src/middlewares/auth.ts
> +    return ctx.assert(user, 404, 'User not found. Please login!')
Давай использовать `ctx.throw` и `@hapi/boom`

2021-12-02 23:01 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.updateOne({ id })
К слову, пользователи могут редактировать или удалять чужие сообщения?

2021-12-03 17:53 UTC, chmsv commented on src/controllers/messages.ts
> +    return await MessageModel.updateOne({ id })
- почему-то без await prettier выдает ошибку: "Async method 'editMessage' has no 'await' expression".

- добавила проверку по id и user

2021-12-04 17:58 UTC, backmeupplz requested changes

2021-12-04 17:58 UTC, backmeupplz commented on src/controllers/login.ts
> +    @Body({ required: true }) email: string,
Добавь валидацию

2021-12-04 17:58 UTC, backmeupplz commented on src/controllers/login.ts
> +    console.log(name, email)
Не пушь лишние console.log в гит

2021-12-04 17:58 UTC, backmeupplz commented on src/middlewares/auth.ts
> +  const token = ctx.headers['authorization']
Давай не будем использовать `[]`

2021-12-04 17:58 UTC, backmeupplz commented on src/middlewares/auth.ts
> +  ctx.state.user = await verify(token)
Как насчет найти именно объект юзера в бд?

2021-12-04 17:58 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.find({ id, text, user })
В `amala` можно без `return await`, просто делай `return`

2021-12-04 20:07 UTC, chmsv commented on src/controllers/messages.ts
> +    return await MessageModel.find({ id, text, user })
без await eslint ругается: "Async method 'editMessage' has no 'await' expression".

2021-12-04 22:07 UTC, backmeupplz requested changes

2021-12-04 22:07 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return await MessageModel.find({ id, text, user })
Так надо делать `return` :)

2021-12-05 18:30 UTC, backmeupplz requested changes

2021-12-05 18:30 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +    return ctx.throw(notFound('User not found. Please login!'))
Это же `message not found`. Давай без текста, просто кидать `notFound()`

2021-12-05 18:30 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +  if (!isEqual(message.user, user._id)) {
Это же можно заменить на `===`, нет?

2021-12-05 18:30 UTC, backmeupplz commented on src/middlewares/auth.ts
> +  const user = await UserModel.findOne({ filter: token })
Что за `filter`?

2021-12-05 18:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    return newMessage
Просто сделай `return new MessageModel({ text, user }).save()`, смысла делать это в две строки мало

2021-12-05 18:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    @Body({ required: true }) { text }: Message,
Ты же запрашиваешь сообщение по id, зачем тебе передавать сюда передавать текст?

2021-12-05 18:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const foundMessage = await MessageModel.find({ id, text, user })
Но ведь в @State будет `message` :)

2021-12-05 18:30 UTC, backmeupplz commented on src/controllers/messages.ts
> +    const editedMessage = await MessageModel.findOneAndUpdate(
А зачем снова искать? Сообщение же есть в `@State`

2021-12-05 19:21 UTC, chmsv commented on src/middlewares/checkUser.ts
> +  if (!isEqual(message.user, user._id)) {
lodash isEqual позволяет делать глубокое сравнение объектов, думала, он больше подходит. заменила на `===`

2021-12-05 19:22 UTC, chmsv commented on src/middlewares/auth.ts
> +  const user = await UserModel.findOne({ filter: token })
это мои неудачные попытки понять, откуда ошибка в postman. убрала этот блок, вернула первый вариант файла

2021-12-05 19:41 UTC, backmeupplz requested changes

2021-12-05 19:41 UTC, backmeupplz commented on src/middlewares/checkUser.ts
> +  if (!(message.user === user._id)) {
Выглядит, как `!==` :)

2021-12-16 19:50 UTC, closed without merging