Crud messages
Borodutch/backend-starter pull request #90
Opened 2021-12-30 14:16 UTC by vapapaiva

add CRUD messages

2022-01-01 16:03 UTC, backmeupplz requested changes

2022-01-01 16:03 UTC, backmeupplz commented on src/validators/ManualLogin.ts
> +export default class ManualLogin {
Давай назовем это `EmailLogin`

2022-01-01 16:03 UTC, backmeupplz commented on src/validators/ManualLogin.ts
> +  email?: string
Это обязательный параметр

2022-01-01 16:03 UTC, backmeupplz commented on src/models/message.ts
> +  user_id!: string
Не используй snake case в TS, используй camel case

2022-01-01 16:03 UTC, backmeupplz commented on src/models/message.ts
> +  user_id!: string
Тут должен быть `ref`, а не `string`, почитай про них в typegoose

2022-01-01 16:03 UTC, backmeupplz commented on src/helpers/createBoomError.ts
> +export default function createBoomError(
Тебе точно не нужна эта функция. `import { forbidden } from '@hapi/boom'; ctx.throw(forbidden('This route is forbidden'))`

2022-01-01 16:03 UTC, backmeupplz commented on src/controllers/login.ts
> +  @Post('/manual')
Давай назовем этот путь `email`

2022-01-01 16:03 UTC, backmeupplz commented on src/controllers/login.ts
> +  async createUserManually(
Не забудь изменить название функции

2022-01-03 17:00 UTC, backmeupplz requested changes

2022-01-03 17:00 UTC, backmeupplz commented on src/controllers/message.ts
> +
Вижу, уже начал делать подобие авторизации. Давай сделаем ее правильно. Создай `middleware`, который будет находитб юзера по `token` в `headers` — и добавлять этого юзера в `ctx.state.user`

2022-01-05 22:28 UTC, backmeupplz requested changes

2022-01-05 22:28 UTC, backmeupplz commented on src/validators/MessageValidators.ts
> +  id!: ObjectId
Все-таки, это все еще будет `string`

2022-01-05 22:28 UTC, backmeupplz commented on src/models/message.ts
> +  userId!: Ref<User>
Это `ref`, можешь просто назвать, например, `author` это поле

2022-01-05 22:28 UTC, backmeupplz commented on src/models/message.ts
> +  @prop({ required: true, ref: mongoose.Schema.Types.ObjectId })
Это не `ref` на `ObjectId`, это `ref: () => User`

2022-01-05 22:28 UTC, backmeupplz commented on src/middleware/attachUser.ts
> +export default async function attachUser(ctx: Context, next: Next) {
Давай назовем это `authorize`

2022-01-05 22:28 UTC, backmeupplz commented on src/middleware/attachUser.ts
> +  return await next()
Почитай про `return await` и как promises связаны с async/await. Тут не нужен await.

2022-01-05 22:28 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await MessageModel.find()
Почитай про `return await`, он тут не нужен

2022-01-05 22:28 UTC, backmeupplz commented on src/controllers/message.ts
> +    return await MessageModel.find()
Может, вернуть все сообщения авторизованного пользователя?

2022-01-05 22:28 UTC, backmeupplz commented on src/controllers/message.ts
> +    const message = await MessageModel.findById(id)
Давай сделаем так, чтобы пользователь мог видеть, редактировать и удалять только свои сообщения

2022-01-05 22:28 UTC, backmeupplz commented on src/validators/MessageValidators.ts
> +import { IsMongoId, IsNotEmpty, IsString } from 'amala'
Давай просто назовем это `validators/message.ts`. Смысл дважды писать `validator`? :)

2022-01-05 22:28 UTC, backmeupplz commented on src/controllers/message.ts
> +        forbidden(
Факт того, что сообщение по id существует — это дополнительная информация, которую нельзя давайть другим пользователям. Нужно вернуть 404.

2022-01-06 17:59 UTC, vapapaiva commented on src/controllers/message.ts
> +    return await MessageModel.find()
Сделал, теперь юзер может получить/отредактировать/удалить только свои сообщения

2022-01-06 17:59 UTC, vapapaiva commented on src/middleware/attachUser.ts
> +  return await next()
спасибо, не знал про это!

2022-01-06 18:20 UTC, vapapaiva commented on src/validators/MessageValidators.ts
> +  id!: ObjectId
Сделал. Понял так: мы валидируем уже через @IsMongoId и этого достаточно для выполнения задачи; При этом в запросе все равно передаём только стрингу, поэтому бессмысленно определять тут тип как ObjectId

2022-01-06 21:35 UTC, backmeupplz requested changes

2022-01-06 21:35 UTC, backmeupplz commented on src/middleware/authorize.ts
> +  return await next()
Тебе тут не нужен `await`

2022-01-06 21:35 UTC, backmeupplz commented on src/controllers/message.ts
> +    return MessageModel.find({ author: ctx.state.user._id })
Как насчет декоратора `@CurrentUser`? :) И тебе не нужно тут использовать `_id`, можешь использовать прямо объект юзера.

2022-01-06 21:35 UTC, backmeupplz commented on src/controllers/message.ts
> +    if (
Ты делаешь это три раза. Как насчет сделать middleware, который будет находить сообщение, проверять его авторство — и добавлять его в `ctx.state`?

2022-01-08 15:52 UTC, vapapaiva commented on src/controllers/message.ts
> +    if (
Вынес в middleware
Только теперь я проверяю что id валидный ObjectId через if/else. Не разобрался, как проверять это с помощью валидатора MessageId (как было до того, как вынес в middleware) — так и не смог разобраться как определить тип ctx так, чтобы в ctx.params.id ожидать именно MessageId:
`
// не сработал ни такой
interface MyContext extends Context { params: { id: MessageId } }
ctx: MyContext
// ни такой варианты
ctx: Context & { params: { id: MessageId } }
// не смог нагуглить как ещё это можно сделать и решил пойти через if/else. Оч интересно, ок ли это
`

2022-01-09 16:48 UTC, backmeupplz requested changes

2022-01-09 16:48 UTC, backmeupplz commented on src/validators/Message.ts
> +  @IsNotEmpty()
А точно нужно `IsNotEmpty`? Если тут нужно — то нужно и везде? Разве `IsString` не проверяет на пустоту строки?

2022-01-09 16:48 UTC, backmeupplz commented on src/middleware/findUserMsg.ts
> +      // ctx.state.user._id.toString() != msg?.author?.toString()
Не пушь закомментированный код на гитхаб

2022-01-09 16:48 UTC, backmeupplz commented on src/middleware/findUserMsg.ts
> +  if (isValidObjectId(ctx.params.id)) {
Лучше сначала проверять на ошибки, а потом продолжать обычную работу. Например:
`if (!isValidObjectId(ctx.params.id)) { return ctx.throw(badRequest('MessageId must be mongoose ObjectId type')) }`

2022-01-09 16:48 UTC, backmeupplz commented on src/middleware/findUserMsg.ts
> +  if (isValidObjectId(ctx.params.id)) {
таким образом, у тебя не будет `if nesting hell`

2022-01-09 16:48 UTC, backmeupplz commented on src/middleware/findUserMsg.ts
> +    const msg = await MessageModel.findById(ctx.params.id)
Не сокращай зазря `message` до `msg`

2022-01-09 16:48 UTC, backmeupplz commented on src/controllers/message.ts
> +  getAllMessages(@CurrentUser() user: User) {
А если назовешь переменную `author`, то сможешь сделать `find({ author })`

2022-01-09 16:48 UTC, backmeupplz commented on src/controllers/message.ts
> +    @CurrentUser() user: User,
Тут тоже можешь назвать переменную `author`

2022-01-09 16:48 UTC, backmeupplz commented on src/controllers/message.ts
> +    return message
А можешь просто сделать `return MessageModel.create(...)`

2022-01-09 16:48 UTC, backmeupplz commented on src/controllers/message.ts
> +    return `You've deleted message ${ctx.state.msg}`
Давай возвращать json, если мы везде его возвращаем. Например, `{ success: true }`

2022-01-10 13:43 UTC, vapapaiva commented on src/validators/Message.ts
> +  @IsNotEmpty()
Если убираю `IsNotEmpty` и пытаюсь создать `massage` с пустой строкой `{ "text": "" }`, то сервер выдаёт `Internal Server Error` (в консоль пишет `Path 'text' is required.`). `IsString` проверяет `if a given value is a real string`, она пропускает пустые строки. 

Насколько понимаю да, аналогичную проверку хорошо бы делать в EmailLogin валидаторе (проверил, там та же ошибка падает, если передать пустые строки вместо имени/имейла: `{ "name": "", "email": "" }`

2022-01-10 14:51 UTC, closed without merging