added CRUD for messages
Borodutch/backend-starter pull request #99
Opened 2022-03-08 13:12 UTC by imikl

Create via POST, read - GET, update - PATCH & DELETE as himself.
Checked with postman. Can be improved with some user check middleware

2022-03-17 16:20 UTC, backmeupplz requested changes

2022-03-17 16:20 UTC, backmeupplz commented on package-lock.json
> +{
Этот файл не нужен, используй `yarn`

2022-03-17 16:20 UTC, backmeupplz commented on package.json
>      "koa-bodyparser": "^4.3.0",
В этом файле не должно быть изменений

2022-03-17 16:20 UTC, backmeupplz commented on yarn.lock
>    version: 5
В этом файле не должно быть изменений

2022-03-17 16:20 UTC, backmeupplz commented on src/models/Message.ts
> +  user_id?: number
В TS не используется snake case, используй везде camel case

2022-03-17 16:20 UTC, backmeupplz commented on src/models/Message.ts
> +  messageData!: string
Достаточно иметь просто `text!: string`. Если это `required`, то так и напиши

2022-03-17 16:20 UTC, backmeupplz commented on src/models/Message.ts
> +  @prop({ index: true, lowercase: true })
Почитай, что такое `index`, и почему здесь не стоит его включать. `lowercase` тоже не нужен

2022-03-17 16:20 UTC, backmeupplz commented on src/models/Message.ts
> +  user_id?: number
Вместо этого, используй `ref` из `typegoose`

2022-03-17 16:20 UTC, backmeupplz commented on src/models/Message.ts
> +  company_name?: string
Это поле не нужно

2022-03-17 16:20 UTC, backmeupplz commented on src/models/Message.ts
> +export async function findMessage(messageOptions: { _id: string }) {
Не дестракти аргументы — в этом мало смысла, особенно когда аргумент один

2022-03-17 16:20 UTC, backmeupplz commented on src/models/Message.ts
> +    throw new Error('Message not found')
Не кидай простые ошибки, кидай `@hapi/boom` ошибки

2022-03-17 16:20 UTC, backmeupplz commented on src/controllers/message.ts
> +  async getMessage(@Params('id') _id: string) {
Валидируй параметры

2022-03-17 16:20 UTC, backmeupplz commented on src/controllers/message.ts
> +import Message from '@/validators/Message'
Это не сообщение, это валидатор сообщения

2022-03-17 16:20 UTC, backmeupplz commented on src/controllers/message.ts
> +  deleteMessage(@Params('id') _id: string) {
Валидируй параметры

2022-04-05 20:03 UTC, imikl commented on src/controllers/message.ts
> +    const msg = await findAndUpdateMessage({
Для обновления выводимого сообщения (иначе оно остаётся без изменений). Так же указано в документации по mongoose с findOneAndUpdate() - там используется findOne() перед выводом измененных параметров

2022-04-07 14:54 UTC, backmeupplz requested changes

2022-04-07 14:54 UTC, backmeupplz commented on src/controllers/message.ts
> +    const currUser = await findOrCreateUser({ name })
Сокращать имена переменных зазря — бессмысленно, только код сложнее читать

2022-08-02 14:35 UTC, backmeupplz requested changes

2022-08-02 14:35 UTC, backmeupplz commented on src/validators/User.ts
> +export default class UserId {
Выглядит, как будто тут должен быть только `id` — и больше ничего

2022-08-02 14:35 UTC, backmeupplz commented on src/validators/Message.ts
> +  _id!: ObjectId
Тебе не нужно тут указывать `_id`

2022-08-02 14:35 UTC, backmeupplz commented on src/middleware/UserVerify.ts
> +      userId = verify(token)['_id'] as string
Никогда не используй `['...']`, это убивает типизацию

2022-08-02 14:35 UTC, backmeupplz commented on src/middleware/UserVerify.ts
> +  let currentUser = null
Тебе не нужны тут лишние переменные

2022-08-02 14:35 UTC, backmeupplz commented on src/middleware/UserVerify.ts
> +export default async function UserVerify(ctx: Context, next: Next) {
Тебе не нужно называть единственную функцию с дефолтным экспортом

2022-08-02 14:35 UTC, backmeupplz commented on src/middleware/UserVerify.ts
> +  if (token) {
А если его нет?

2022-08-02 14:35 UTC, backmeupplz commented on src/middleware/UserVerify.ts
> +    if (!currentUser || !(userId == currentUser['_id'].toString())) {
Есть поле `id` у всех объектов из монги, это и есть `_id.toString()`

2022-08-02 14:35 UTC, backmeupplz commented on src/middleware/UserVerify.ts
> +    } as ValidUser)
Тебе не нужно тут кастовать тип

2022-08-02 14:35 UTC, backmeupplz commented on src/models/Message.ts
> +  text!: ValidMessage['text']
Это просто `string`, тебе не нужно использовать тут `ValidMessage['text']`

2022-08-02 14:35 UTC, backmeupplz commented on src/models/Message.ts
> +  @prop({ ref: () => User, required: true })
Почитай про `index` у `typegoose`

2022-08-02 14:35 UTC, backmeupplz commented on src/models/Message.ts
> +export async function findAllMessagesByUser(user: User) {
Тебе не нужны дополнительные функции в этом файле. Экспортируй только `MessageModel` и `Message`

2022-08-02 14:35 UTC, backmeupplz commented on src/models/User.ts
> +    user.token = await sign({ _id: user._id as unknown as string })
В этом файле не должно быть изменений

2022-08-02 14:35 UTC, backmeupplz commented on src/controllers/message.ts
> +  @Flow(UserVerify)
Если используешь этот `@Flow` везде, просто поставь его перед `@Controller` :)

2022-08-02 14:35 UTC, backmeupplz commented on src/controllers/message.ts
> +import UserVerify from '@/middleware/UserVerify'
Названо немного косо. Может, `authenticate`?

2022-08-02 14:35 UTC, backmeupplz commented on src/controllers/message.ts
> +    return findAllMessagesByUser(user)
Почему не сделать просто `return MessageModel.find({ author })`? :)

2022-08-02 14:35 UTC, backmeupplz commented on src/controllers/message.ts
> +    @Body({ required: true }) text: ValidMessage['text'],
Странный какой-то тип валидатора. Смотри, как все сделано в эндпоинте логина. Скорее, должно быть `@Body({...}) { text }: MessageBody`

2022-09-19 21:39 UTC, closed without merging